### PR TITLE
Add lower level readme to pull readme into artifactory

### PR DESCRIPTION
**Pull request by AjayTripathy**
I actually need to roll this into a release to test that artifactory pulls this up correctly.

### CODE REVIEW

**Comment by dwbrown2** [comment]
LGTM if you guys are comfortable with the duplication

**Review by dwbrown2 — APPROVED** [review]

**Comment by dwbrown2** [comment]
Wait, sorry is this really the README you want to use? Why not use the one from this repo vs cost-model?

**Comment by AjayTripathy** [comment]
I'm ok either way-- the helm README.md seemed more like helm instructions than what we want to show on artifactory (features splash page vs helm specific information).

**Comment by dwbrown2** [comment]
I think we definitely want to share helm config options, etc on artifact hub

**Comment by dwbrown2** [comment]
Can we get this in for this week's release?

**Comment by AjayTripathy** [comment]
Yes, can we figure out what we actually want in the readme? I think a view
of our open source is fine and you can come to the helm chart itself for
documentation, see for example the readme here
https://artifacthub.io/packages/helm/prometheus-community/prometheus

**Comment by dwbrown2** [comment]
I'm confused a bit... why would you do anything other than this? https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/README.md

**Comment by AjayTripathy** [comment]
Sure, that's fine. updated.

**Pull request merged**
