### PR TITLE
increment cluster controller version to use new status endpoint

### PR DESCRIPTION
**Pull request by ameijer**

### CODE REVIEW

**Review by nickcurie — APPROVED** [review]
LGTM

**Comment by chipzoller** [comment]
Would you kindly also send a PR to bump this tag in the EKS values file? And both need to be cherry picked, correct?

**Comment by ameijer** [comment]
for your consideration, chip: https://github.com/kubecost/cost-analyzer-helm-chart/pull/3138

**Comment by ameijer** [comment]
both will need to go to 2.1, yes. let me tag accordingly

**Comment by chipzoller** [comment]
Thank you

**Pull request merged**
