### PR TITLE
Added cAdvisor metric "machine_cpu_cores"

### PR DESCRIPTION
**Pull request by rossfisherkc**
## What does this PR change?
Customer wishes to use Grafana and is missing "machine_cpu_cores" metric that cAdvisor provides

## Does this PR rely on any other PRs?
No

## How does this PR impact users? (This is the kind of thing that goes in release notes!)
This adds `machine_cpu_cores` to scraped metrics from cAdvisor (https://github.com/google/cadvisor/blob/master/docs/storage/prometheus.md#prometheus-hardware-metrics)

## Links to Issues or ZD tickets this PR addresses or fixes
https://kubecost.zendesk.com/agent/tickets/4139

## Have you made an update to documentation?
Will update once merged:
https://docs.kubecost.com/architecture/user-metrics#cadvisor

### CODE REVIEW

**Comment by michaelmdresser** [comment]
@AjayTripathy is cardinality a concern here? I assume impact is relatively small, given that this (probably?) scales with node count, not container count

**Comment by thomasvn** [comment]
For reference, [here is the Grafana dashboard](https://github.com/kubecost/cost-analyzer-helm-chart/blob/v1.103/cost-analyzer/deployment-utilization.json#L174) which references the `machine_cpu_cores` metric.

**Comment by chipzoller** [comment]
What is the status with this one?

**Comment by rossfisherkc** [comment]
> What is the status with this one?

Stale, can likely close unless we think it still has value cc @thomasvn

**Pull request closed without merging**
