### PR TITLE
feat: Support priority class in various cost-analyzer components and thanos

### PR DESCRIPTION
**Pull request by gracedo**
## What does this PR change?
- Fix `priorityClassName` default values to empty strings `""` (instead of `[]`)
- Add `priorityClassName` support to cost-analyzer `awsstore`, `remoteWrite.postgres` and `clusterController` deployments
- Add `priorityClassName` support to thanos deployments
- Add `priorityClassName` support to grafana deployment

## Does this PR rely on any other PRs?

- 
- 

## How does this PR impact users? (This is the kind of thing that goes in release notes!)
Adds the ability to set priority class on awsstore, postgres, cluster controller and thanos deployments.

## Links to Issues or ZD tickets this PR addresses or fixes

- 
-

### CODE REVIEW

**Review by msdolbey — APPROVED** [review]
Thanks 👍

**Comment by gracedo** [comment]
@mbolt35 @thomasvn would appreciate some reviews on this, thank you!

**Comment by thomasvn** [comment]
@gracedo This looks good to me, thanks for templatizing the `priorityClassName`!

Out of curiosity, what is your current ordering of priority for deploying each of these services? Or are they all set to the same priority?

**Review by thomasvn — APPROVED** [review]

**Comment by gracedo** [comment]
@thomasvn thanks for the review! We plan on setting all of the kubecost components to the same priority for now

**Pull request merged**
