### PR TITLE
[ENG-2729] Add resource reference files for kubecostProductConfigs.savingsRecommendationsAllowLists

### PR DESCRIPTION
**Pull request by biancaburtoiu**
## What does this PR change?
This PR adds 3 resource files:
- `cost-analyzer/savings-recommendations-allow-lists-aws.yaml`
- `cost-analyzer/savings-recommendations-allow-lists-gcp.yaml`
- `cost-analyzer/savings-recommendations-allow-lists-azure.yaml`

These files contain **the complete lists of supported instance types for the custom allow lists feature** in Savings Recommendations - see https://kubecost.atlassian.net/browse/ENG-2653

The lists are in YAML format for users to be able to easily copy paste their desired items into their `values.yaml` file at:
```yaml
kubecostProductConfigs:
    savingsRecommendationsAllowLists:
        AWS: 
            - t2.small
            - ...
        GCP:
            - ...
         Azure:
            - ...
```

The URLs for these files will be shared as reference in the public API docs for this page, under this PR: https://github.com/kubecost/docs/pull/1123

## Does this PR rely on any other PRs?
Public docs PR: https://github.com/kubecost/docs/pull/1123

## How does this PR impact users? (This is the kind of thing that goes in release notes!)
Users can refer to a set of resource files for every supported CSP (AWS, GCP, Azure) for the complete lists of supported instance types for custom allow lists in Savings Recommendations.

## Links to Issues or tickets this PR addresses or fixes
https://kubecost.atlassian.net/browse/ENG-2729

## What risks are associated with merging this PR? What is required to fully test this PR?
N/A

## How was this PR tested?
N/A

## Have you made an update to documentation? If so, please provide the corresponding PR.
See public docs PR mentioned above: https://github.com/kubecost/docs/pull/1123

### CODE REVIEW

**Comment by srpomeroy** [comment]
@biancaburtoiu I think it would be best to include the relevant helm keys in these files so that these files could be cloned, modified, and used as a values file.

**Comment by biancaburtoiu** [comment]
> @biancaburtoiu I think it would be best to include the relevant helm keys in these files so that these files could be cloned, modified, and used as a values file.

@srpomeroy I've modified each of the 3 files to include the corresponding keys - just double checking that's what you expected?

**Review by srpomeroy — APPROVED** [review]
Looks good @biancaburtoiu 

cc: @jessegoodier in case you care about folder structure or anything else.

**Comment by chipzoller** [comment]
I had to fix your permissions (the bot requires direct account addition, not group membership). Please try again.

**Comment by jessegoodier** [comment]
@biancaburtoiu amazing work! 
@srpomeroy I figured that these are similar in function to the other value files in that folder. We discussed on slack.

**Pull request merged**
