### PR TITLE
Update values.yaml

### PR DESCRIPTION
**Pull request by dwbrown2**
## What does this PR change?
Minor copy changes for labels block

### CODE REVIEW

**Review by JesseGoodier — APPROVED** [review]
LGTM

**Comment by Adam-Stack-PM** [comment]
@dwbrown2 Friendly nudge.  If you would like this in v1.98 would be great if you could merge first thing in the morning.

**Comment by Adam-Stack-PM** [comment]
@AjayTripathy Thank you.

**Comment by Adam-Stack-PM** [comment]
Release Tracking v1.98

**Pull request merged**
