### PR TITLE
added ability to set namespace for cost-analyzer resources and overwr…

### PR DESCRIPTION
**Pull request by cten**
added ability to set namespace for cost-analyzer resources and overwrite namespace for thanos resources

### CODE REVIEW

**Comment by AjayTripathy** [comment]
Thanks @cten -- looks like this fixes https://github.com/kubecost/cost-analyzer-helm-chart/issues/1016 . We'll test on our end and look to get this merged soon!

**Comment by cten** [comment]
My team currently is using this branch, it should still support those who use Helm normally. The logic is to explicitly take the namespace used by Helm and set it on all resources. We used this to deploy our kubecost and worked recently to upgrade from 1.84 to 1.85.

**Comment by kbrwn** [comment]
@cten This change did not work for all resources deployed by the cost-analyzer helm chart. I tested several `--set` variations and the desired namespace was not used for prometheus resources.

**Comment by keithhand** [comment]
> @cten This change did not work for all resources deployed by the cost-analyzer helm chart. I tested several `--set` variations and the desired namespace was not used for prometheus resources.

From what I see, the Thanos chart looks changed, but it seems like the Grafana, Prometheus, and KSM sub-charts all still need to be updated before all the resources will deploy correctly.

**Comment by Adam-Stack-PM** [comment]
Marking as stale because this PR has had no recent activity. It will be closed in seven days if no further activity occurs.

**Pull request closed without merging**
