### PR TITLE
update test in ci-cd, remove k8s image from helm repo

### PR DESCRIPTION
**Pull request by cliffcolvin**
Signed-off-by: Cliff Colvin <ccolvin@kubecost.com>

## What does this PR change?
Remove k8s image from helm, and insert it only during ci/cd. This will assist in passing helm scans.

## Does this PR rely on any other PRs?
NA

## How does this PR impact users? (This is the kind of thing that goes in release notes!)
NA, cicd workflow only

## What risks are associated with merging this PR? What is required to fully test this PR?
NA

## How was this PR tested?
Locally

## Have you made an update to documentation? If so, please provide the corresponding PR.
NA

### CODE REVIEW

**Review by JesseGoodier — APPROVED** [review]

**Comment by cliffcolvin** [comment]
branch build is still pulling from develop. We will merge, test in new pr and if issues fix/revert.

**Review by chipzoller — COMMENTED** [review]
I don't think this is the right approach. Removing the test will prevent users from being able to perform a basic e2e smoke test on Kubecost. It also impacts, if I recall, marketplace catalogs like Google because they require the test be in place. If the idea is to simply quiet the scanners on our side, I think we can just omit the test command.

**Comment by cliffcolvin** [comment]
> I don't think this is the right approach. Removing the test will prevent users from being able to perform a basic e2e smoke test on Kubecost. It also impacts, if I recall, marketplace catalogs like Google because they require the test be in place. If the idea is to simply quiet the scanners on our side, I think we can just omit the test command.

@chipzoller you're saying we need the test in place in the packaged chart?

**Comment by chipzoller** [comment]
I'm not sure if this is specifically a "need", but I do know that a test was required by some marketplace. Can't remember if that was Google or Amazon.

What is the overall motivation for removing this test?

**Comment by cliffcolvin** [comment]
Its definitely not any major issue. Any tool that looks for images in the chart sees k8s and it has vulns. Easy enough to explain away, its not actually used in our application when you install it.

**Comment by cliffcolvin** [comment]
Given the feedback here I'm closing this.

**Pull request closed without merging**
