### PR TITLE
Grafana updates

### PR DESCRIPTION
**Pull request by JesseGoodier**
## What does this PR change?
- Fix grafana dashboard for low disk utilization link. 
- Add dashboards for network services and aggregator metrics
- Reorganization of the dashboards to dedicated folder

## Does this PR rely on any other PRs?
No

## How does this PR impact users? (This is the kind of thing that goes in release notes!)

- Fix grafana dashboard for low disk utilization link. 
- Add dashboards for network services and aggregator metrics
- Reorganization of the dashboards to dedicated folder

## What risks are associated with merging this PR? What is required to fully test this PR?
Low risk

## How was this PR tested?
Helm upgrade against qa environments

## Have you made an update to documentation? If so, please provide the corresponding PR.
NA

### CODE REVIEW

**Comment by jessegoodier** [comment]
@thomasvn The one modified dashboard is currently broken, this fixes it.
The new ones work, and are not linked from UI in general (yet?)

Please let me know if you have any concerns.

**Comment by jessegoodier** [comment]
Note: this will be 2.3. removed the 2.2 cherry-pick label.

**Review by thomasvn — APPROVED** [review]
Awesome. Thanks for the new dashboards, and also for re-organizing the existing ones.

**Pull request merged**
