### PR TITLE
Template fixes

### PR DESCRIPTION
**Pull request by chipzoller**
## What does this PR change?

* Updates to the PR template
* Changes issue template for feature requests to use GitHub forms
* README refinements/updates
* Removes stale and/or disabled workflows that are obviated by past changes
* Updates .gitignore with common, modern dev paths and files

## Does this PR rely on any other PRs?

No

## How does this PR impact users? (This is the kind of thing that goes in release notes!)

Only impacts the user experience in filing for issues on this repo.

## Links to Issues or ZD tickets this PR addresses or fixes

N/A

## What risks are associated with merging this PR? What is required to fully test this PR?

Purely UX related when interacting with this repo. No chart modifications are made.

## How was this PR tested?

Local testing.

## Have you made an update to documentation?

No

### CODE REVIEW

**Review by srpomeroy — APPROVED** [review]
Awesome work. LGTM

**Comment by thomasvn** [comment]
@chipzoller Nice work! Did you need to rename `feature_request.md` -> `feature_request.yaml`? Currently, the feature request template isn't showing up https://github.com/kubecost/cost-analyzer-helm-chart/issues/new/choose

**Comment by chipzoller** [comment]
Dang it, sorry about that. Fixed in #2521. This is why the review process is so important!

**Comment by srpomeroy** [comment]
Whoops. My bad as well. Sorry for missing that!

**Comment by chipzoller** [comment]
My mistake. It's fixed so now you can see the new and improved feature request using GitHub Forms.

**Pull request merged**
