### PR TITLE
Add missing container security context in prometheus server statefulset

### PR DESCRIPTION
**Pull request by spiarh**
## What does this PR change?
Allow configuring the security context of the prometheus server pod when used in a `StatefulSet`.

## Does this PR rely on any other PRs?
No

## How does this PR impact users? (This is the kind of thing that goes in release notes!)
Ensure `.Values.prometheus.server.containerSecurityContext` is actually configuring the security context of the prometheus server pod.

## How was this PR tested?
Using `helm template ./` and the following `values.yaml`:

```yaml
prometheus:
  server:
    replicaCount: 2
    statefulSet:
      enabled: true
    securityContext:
      fsGroup: 1001
      runAsGroup: 1001
      runAsNonRoot: true
      runAsUser: 1001
      seccompProfile:
        type: RuntimeDefault
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      runAsUser: 1001
      runAsGroup: 1001
      readOnlyRootFilesystem: true
```

### CODE REVIEW

**Review by chipzoller — APPROVED** [review]
LGTM and tested ok

**Review by thomasvn — APPROVED** [review]
Thanks @spiarh !

**Comment by thomasvn** [comment]
@chipzoller Do you think this should go in v2.4.x or v2.5.0?

**Comment by chipzoller** [comment]
Seems pretty straightforward for 2.4.

**Pull request merged**
