### PR TITLE
Add labels for basic-health tester Pod

### LINKED ISSUE #3115: [Feature] Use labels for basic-health pod
### Problem Statement

I am not able to deploy cost-analyzer to kubernetes because kyverno policies expect for few labels to be present in basic-health pod

```shell
check-for-labels: 'validation error: The label `[app.kubernetes.io/name`] is required.
    rule check-for-labels failed at path /metadata/labels/'
```

### Solution Description

1. Use same labels for basic health pods as for other cost-analyzer components

### Alternatives

_No response_

### Additional Context

_No response_

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/ISSUE_GUIDELINES.md) and this is a feature request only for the Helm chart.
- [X] I have searched other issues in this repository and mine is not recorded.

### PR DESCRIPTION
**Pull request by chipzoller**
Signed-off-by: chipzoller <chipzoller@gmail.com>

## What does this PR change?

Adds standard K8s labels for basic-health Pod.

## Does this PR rely on any other PRs?

No

## How does this PR impact users? (This is the kind of thing that goes in release notes!)

Allows policy which requires these labels to pass.

## Links to Issues or tickets this PR addresses or fixes

Closes #3115

## What risks are associated with merging this PR? What is required to fully test this PR?

None, it's only labels and only for the test which is only deployed when executing a `helm test` command.

## How was this PR tested?

Locally

## Have you made an update to documentation? If so, please provide the corresponding PR.

N/A

### CODE REVIEW

**Comment by mpostument** [comment]
Can this change to be included in 1.8.x version? I haven't migrated to 2.x yet

**Comment by chipzoller** [comment]
It would be 1.108.x and I can cherry pick it there. Not sure yet if we will have another patch release in that release train, but if so this will be included.

**Review by JesseGoodier — APPROVED** [review]

**Pull request merged**
