### PR TITLE
Delete templates/values that are no longer used

### PR DESCRIPTION
**Pull request by thomasvn**
## What does this PR change?

Delete templates/values that are no longer used. Additionally, deleted comments.

**What comments got deleted?** Redundant or commonly known expressions. As an example, for the line `tolerations: []`, I've removed the comment "Node tolerations for alertmanager scheduling to nodes with taints" and have removed the commented out example. These are common k8s concepts that can be googled. Additionally, I've removed comments from Prometheus and Grafana which were not Kubecost-specific.

**What comments are kept?** Kubecost-specific context that the user should be aware of.

## Does this PR rely on any other PRs?

N/A

## How does this PR impact users? (This is the kind of thing that goes in release notes!)

The following features have been removed from the Helm Chart:

- Kubecost Metrics Exporter
- Ingress to cost-model container Port 9003.
- Prometheus PushGateway
- `.Values.kubecostModel.etlBucketConfigSecret`
- Cost-analyzer Network Policy
- Prometheus Network Policy
- Kubecost Cloud Agent. `kubecost-agent-secret-template.yaml`. `kubecost-agent-secretprovider-template.yaml`.
- `azure-storage-config-secret.yaml`

## Links to Issues or tickets this PR addresses or fixes

N/A

## What risks are associated with merging this PR? What is required to fully test this PR?

Features which are determined to be lesser used are being removed in this PR. I recommend we let this sit in our nightly environments for some time before shipping.

## How was this PR tested?

```
ct lint --chart-dirs=cost-analyzer/ --charts cost-analyzer/ --validate-maintainers=false
```

```
helm template cost-analyzer --debug
```

```
# Install my local helm chart to a cluster to get it running
helm upgrade -i thomasn-nightly-local ./cost-analyzer
```

## Have you made an update to documentation? If so, please provide the corresponding PR.

https://github.com/kubecost/docs/pull/1150

### CODE REVIEW

**Comment by chipzoller** [comment]
Bless you for this work, sir.

**Comment by srpomeroy** [comment]
I see you are moving third-party resources to subfolders. I am not sure why we flattened them in the first place, as they used to be in subfolders. 

I am not familiar enough with Helm to know if it cares about directory structure. Do any considerations need to be taken by changing the file paths?

**Comment by thomasvn** [comment]
@srpomeroy Good call. I'll deploy this chart and see if the paths cause any issues for Prometheus or Grafana!

**Comment by thomasvn** [comment]
@srpomeroy I've tested by deploying my local chart changes to a cluster. Grafana and Prometheus look to be working as expected!

**Review by JesseGoodier — APPROVED** [review]
All of my tests are passing.

Appreciate your efforts on this one, it is huge.

**Comment by chipzoller** [comment]
Bunch of conflicts here now. Probably need to get this in soon after resolving so they don't keep popping up.

**Comment by thomasvn** [comment]
@chipzoller Will do. Haven't been able to return to this work, but will try to get it resolved & merged ASAP.

**Comment by thomasvn** [comment]
I've resolved all merge conflicts and have tested locally with default values:

```
helm upgrade -i thomasn-nightly-local ./cost-analyzer
```

I'm going to go ahead and merge now to let this test in our nightly environments.

**Comment by chipzoller** [comment]
Sent https://github.com/kubecost/docs/pull/1151 to fix some links.

**Pull request merged**
