### PR TITLE
bumping deprecated apiVersions to support k8s 1.16+

### PR DESCRIPTION
**Pull request by kkunkel**
These deprecated apiVersions are no longer supported by default in Kubernetes 1.16+
https://kubernetes.io/docs/setup/release/notes/#deprecations-and-removals

Signed-off-by: Kevin Kunkel <kkunkel@indeed.com>

### CODE REVIEW

**Comment by dwbrown2** [comment]
Greatly appreciate the PR, @kkunkel! Looks good based on everything I see. We should be able to get tested soon.

**Comment by dwbrown2** [comment]
Finishing testing soon. Here's additional documentation: https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

**Comment by dwbrown2** [comment]
I've been seeing this error during testing on v1.12. 

```
Error: validation failed: error validating "": error validating data: ValidationError(Deployment.spec): missing required field "selector" in io.k8s.api.apps.v1.DeploymentSpec
```

Investigating further.

**Comment by kkunkel** [comment]
@dwbrown2, I've updated the Deployments with missing selectors

**Comment by dwbrown2** [comment]
You beat me to it! Thanks so much for this. Changes LGTM. 

@AjayTripathy can you merge when ready?

**Pull request merged**
