### PR TITLE
Add error messages

### PR DESCRIPTION
**Pull request by ghost**
## What does this PR change?
Bumps the image tag with a new (semver compliant) Forecasting image that uses better http error codes and new more informative messages about things going wrong.

## Does this PR rely on any other PRs?
https://github.com/kubecost/kubecost-modeling/pull/37

## How does this PR impact users? (This is the kind of thing that goes in release notes!)
Users should now receive the correct message for unsupported aggregations and a 501, a 400 and more informative error for malformed requests, and a 503 and helpful message when a valid model is untrained (usually courtesy of upstream data issues)

## What risks are associated with merging this PR? What is required to fully test this PR?
Pretty minimal risk

## How was this PR tested?
Locally!

## Have you made an update to documentation? If so, please provide the corresponding PR.
n/a

### CODE REVIEW

**Review by michaelmdresser — APPROVED** [review]

**Review by saweber — APPROVED** [review]

**Comment by chipzoller** [comment]
FYI calling the cherry pick bot has some finicky permissions requirements; users who call for it must be added directly and cannot be part of a team.

**Comment by nealormsbee** [comment]
^ That would have been nice info to get when I asked why it seemed not to be working in the UI repo, rather than two links to a [docs page](https://github.com/googleapis/repo-automation-bots/tree/main/packages/cherry-pick-bot) that I'd already read.

Any chance you can add individuals from my team? Or do I need Thomas for that.

**Comment by chipzoller** [comment]
> ^ That would have been nice info to get when I asked why it seemed not to be working in the UI repo, rather than two links to a [docs page](https://github.com/googleapis/repo-automation-bots/tree/main/packages/cherry-pick-bot) that I'd already read.

We probably didn't know it was the case at that time because it was freshly implemented.

I can add individuals. Who should be added?

**Comment by nealormsbee** [comment]
@rayhatfield @wolfeaustin @jjarrett21 and myself, please and thank you.

**Comment by chipzoller** [comment]
Done

**Pull request merged**
