### PR TITLE
add helm config option to mount ca certs to cost model container (#3760)

### PR DESCRIPTION
**Pull request by mittal-ishaan**
* add helm config option to mount ca certs to cost model container

* update it to be configmap

* shift from config map tp secret

* nit fix

### CODE REVIEW

**Comment by chipzoller** [comment]
Why a secret?

**Comment by mittal-ishaan** [comment]
We wanted to give user an option to mount ca certs inside the constiner. We could have used configMap or secret. went ahead with secret for this one.

**Comment by chipzoller** [comment]
I recommend using a ConfigMap instead as it's the industry standard API resource for certificates.

**Comment by mittal-ishaan** [comment]
thank you. let me correct it then.

**Comment by chipzoller** [comment]
And have you actually verified this will work in our container? I'm skeptical it will because of the need to run a command when adding anchors. Adding to the trust store directly usually does not require this but overwrites the store.

**Review by JesseGoodier — APPROVED** [review]

**Comment by jessegoodier** [comment]
> And have you actually verified this will work in our container? I'm skeptical it will because of the need to run a command when adding anchors. Adding to the trust store directly usually does not require this but overwrites the store.

Thinking an initContainer? 
We have a customer using this now. But let's continue to improve this and then document how to use it correctly.

**Comment by jessegoodier** [comment]
okay- proposing we move to something like this?

https://jfrog.com/help/r/artifactory-how-to-add-custom-ssl-certificates-to-an-artifactory-pod-using-helm-charts/how-to-update-the-ca-certificates-within-the-artifactory-pod

```
artifactory:
  customInitContainers: |
    - name: "sslsetup"
      image: "{{ .Values.initContainerImage }}"
      imagePullPolicy: "{{ .Values.artifactory.image.pullPolicy }}"
      securityContext:
        privileged: true
        runAsUser: 0
        runAsGroup: 0
        runAsNonRoot: false
      command:
        - 'sh'
        - '-c'
        - >
          mkdir -p /etc/pki/ca-trust/extracted/{edk2,java,openssl,pem};
          /usr/bin/update-ca-trust extract;
      volumeMounts:
        - mountPath: "{{ .Values.artifactory.persistence.mountPath }}"
          name: artifactory-volume
        - name: my-certs
          mountPath: "/etc/pki/ca-trust/source/anchors/mycustom.crt"
          subPath: mycustom.crt
        - name: ssl-path
          mountPath: "/etc/pki/ca-trust/extracted"
          readOnly: false
  customVolumes: |
   - name: ssl-path
     emptyDir: {}
   - name: my-certs
     configMap:
       name: my-certs
  customVolumeMounts: |
   - name: my-certs
     mountPath: /etc/pki/ca-trust/source/anchors/mycustom.crt
     subPath: mycustom.crt
   - name: ssl-path
     mountPath: /etc/pki/ca-trust/extracted
```

**Comment by mittal-ishaan** [comment]
yes, this looks better to me. Let me get this done.

**Comment by chipzoller** [comment]
Yes, that's what I am driving at. How does this work unless someone/something executes a command after the new anchors are provided to merge them into the store? Normally on Red Hat you have to run `update-ca-trust` I believe in order to make that happen.

**Comment by mittal-ishaan** [comment]
Yes, we earlier we were expecting the user to run `update-ca-trust` inside the container. but having it done in a init container is better.

**Comment by chipzoller** [comment]
Requiring users run commands inside of a container should always be avoided at all costs. If the initContainer works, that'd be a better approach.

**Comment by chipzoller** [comment]
Superseded by #3763

**Pull request closed without merging**
