### PR TITLE
kubecost aggregator: Support for saml/oidc/ui defined teams

### PR DESCRIPTION
**Pull request by saweber**
## What does this PR change?
Adds support for SAML, SAML filters, and OIDC in Aggregator.

## Does this PR rely on any other PRs?
Yes; https://github.com/kubecost/kubecost-cost-model/pull/1949

## How does this PR impact users? (This is the kind of thing that goes in release notes!)
Adds support for SAML, SAML filters, and OIDC in Aggregator.

## Links to Issues or tickets this PR addresses or fixes
https://kubecost.atlassian.net/browse/SELFHOST-961
https://kubecost.atlassian.net/browse/SELFHOST-962

## What risks are associated with merging this PR? What is required to fully test this PR?
This affects all customers using aggregator with SAML, SAML filtering, or OIDC.

- OIDC functionality is untested; currently there is no test environment. Testing the functionality and correcting issues is in ticket https://kubecost.atlassian.net/browse/SELFHOST-1034.
- Customers using aggregator and SAML will need to configure saml.authSecret and saml.authSecretName so aggregator can parse and validate tokens issued by the cost-model pod. This should be temporary until the cost-model pod is no longer used for front end queries. If they do not, all queries to the aggregator pod will fail with a 403/forbidden.

## How was this PR tested?
Manually

## Have you made an update to documentation? If so, please provide the corresponding PR.
Not yet.

### CODE REVIEW

**Comment by chipzoller** [comment]
Conflicts to resolve here now after merges.

**Comment by chipzoller** [comment]
@saweber, is this PR ready for final review? If so, would you please complete the PR template?

**Comment by saweber** [comment]
No, the work is still in progress.

**Comment by saweber** [comment]
I'm leaving this in a draft state until we merge the required KCM changes.

**Comment by saweber** [comment]
The 'secret' above was already public in this repository (was also a minor merge issue that is resolved).

**Review by JesseGoodier — APPROVED** [review]

**Pull request merged**
