### PR TITLE
FIX grafana service account creation and name

### PR DESCRIPTION
**Pull request by korjek**
## What does this PR change?

right now, service account of cost-analyzer is used in grafana deployment too. So there are two manifests with the same service account name and the last one wins.

## Does this PR rely on any other PRs?

No

## How does this PR impact users? (This is the kind of thing that goes in release notes!)

fixes service account for grafana

## What risks are associated with merging this PR? What is required to fully test this PR?

risk is really low.

## How was this PR tested?

 And this was tested locally.
Helm diff (`monitoring` is a release name)

```
ops, monitoring-kubecost-grafana, Deployment (apps) has changed:
  # Source: ops-monitoring/charts/cost-analyzer/templates/grafana-deployment.yaml
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: monitoring-kubecost-grafana
    namespace: ops
    labels:
      app: grafana
      release: monitoring
      heritage: Helm
  spec:
    replicas: 1
    ...
      spec:
-       serviceAccountName: cost-analyzer
+       serviceAccountName: monitoring-kubecost-grafana
        securityContext:
          fsGroup: 1001
          fsGroupChangePolicy: OnRootMismatch
     ...
ops, monitoring-kubecost-grafana-clusterrolebinding, ClusterRoleBinding (rbac.authorization.k8s.io) has changed:
  # Source: ops-monitoring/charts/cost-analyzer/templates/grafana-clusterrolebinding.yaml
  kind: ClusterRoleBinding
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: monitoring-kubecost-grafana-clusterrolebinding
    labels:
      app: grafana
      release: monitoring
      heritage: Helm
  subjects:
    - kind: ServiceAccount
-     name: cost-analyzer
+     name: monitoring-kubecost-grafana
      namespace: ops
  roleRef:
    kind: ClusterRole
    name: monitoring-kubecost-grafana-clusterrole
    apiGroup: rbac.authorization.k8s.io
ops, monitoring-kubecost-grafana, ServiceAccount (v1) has been added:
-
+ # Source: ops-monitoring/charts/cost-analyzer/templates/grafana-serviceaccount.yaml
+ apiVersion: v1
+ kind: ServiceAccount
+ metadata:
+   labels:
+     app: grafana
+     heritage: Helm
+     release: monitoring
+   name: monitoring-kubecost-grafana
+   namespace: ops
```

## Have you made an update to documentation? If so, please provide the corresponding PR.

Updated README.md

### CODE REVIEW

**Comment by chipzoller** [comment]
Thanks for your contribution here. Please set the base branch to `develop`. `Chart.yaml` does not need to be modified.

**Comment by korjek** [comment]
> Thanks for your contribution here. Please set the base branch to `develop`. `Chart.yaml` does not need to be modified.

@chipzoller as I can see branch `v2.0` (where the bug this PR is fixing comes from) is not merged into `develop`. And if I set base branch to `develop` there will be tons of changes (as I used `v2.0` branch as a source, where the bag was introduced). 

So do you still want me to open PR with merge int `develop` branch?

P.S. I reverted changes to `Chart.yaml`

**Comment by chipzoller** [comment]
All changes must first go to the develop branch and are then cherry picked to release branches.

**Comment by korjek** [comment]
> All changes must first go to the develop branch and are then cherry picked to release branches.

Got it.
Changed base branch to `develop`

**Comment by chipzoller** [comment]
Can you rework this PR so only the required changes are made to `develop`, please?

**Comment by korjek** [comment]
Created https://github.com/kubecost/cost-analyzer-helm-chart/pull/3073 instead

**Pull request closed without merging**
