### PR TITLE
selfsigned cert flags

### PR DESCRIPTION
**Pull request by AjayTripathy**
Why do this?

For onprem users, some s3-like storage systems require a self-signed cert. This is an implementation of method 3 here: https://paraspatidar.medium.com/add-self-signed-or-ca-root-certificate-in-kubernetes-pod-ca-root-certificate-store-cb7863cb3f87

Add selfsigned cert flags. Testing done:

1. kubectl -n kubecost create configmap ca-pemstore — from-file=my-cert.pem
2. helm upgrade kubecost-ajay ./cost-analyzer -f ./cost-analyzer/values.yaml -f ./cost-analyzer/values-thanos.yaml -n kubecost-ajay --set .Values.thanos.store.selfsignedCertConfigMapName ca-pemstore
3. exec into thanos-store and note the file has been added to  /etc/ssl/certs/my-cert.pem

### CODE REVIEW

**Comment by michaelmdresser** [comment]
Do we still want to make this change?

**Comment by AjayTripathy** [comment]
Yes-- I'll look at getting it or something close to it tested and reviewed.

**Comment by AjayTripathy** [comment]
Sure!

**Comment by AjayTripathy** [comment]
@mbolt35 mind taking a look when you can? I'd like to mainline this soon.

**Review by mbolt35 — APPROVED** [review]
Looks fine to me, as long as we have tested, I'm good with adding this

**Pull request merged**
