### PR TITLE
disable configmapReloader by default

### PR DESCRIPTION
**Pull request by JesseGoodier**
## What does this PR change?
Disable Prometheus configMap reloader by default

## Does this PR rely on any other PRs?
No

## How does this PR impact users? (This is the kind of thing that goes in release notes!)
Disable Prometheus configMap reloader by default to reduce containers/images. There is no impact to typical Kubecost installs

## What risks are associated with merging this PR? What is required to fully test this PR?
Users that don't see the release notes and utilize the functionality provided by the bundle prometheus server.

## How was this PR tested?
Helm installs on several environments.

## Have you made an update to documentation? If so, please provide the corresponding PR.
TBD

### CODE REVIEW

**Comment by chipzoller** [comment]
Can we not just yank it out entirely or do you feel that's not safe at this point? Leaving it disabled is still one more image we have to maintain.

**Comment by jessegoodier** [comment]
> Can we not just yank it out entirely or do you feel that's not safe at this point? Leaving it disabled is still one more image we have to maintain.

I'd like to give it a version or two. much easier to rollback this way.

**Comment by chipzoller** [comment]
As discussed, can we also disable the Grafana sidecar as part of this?

**Comment by jessegoodier** [comment]
> As discussed, can we also disable the Grafana sidecar as part of this?

That one needs more work. dashboards don't load without it. I would need to research how to make that happen.

My biggest priority right now is agent config in 2.0

**Review by chipzoller — APPROVED** [review]

**Pull request merged**
