### PR TITLE
helm client version check

### PR DESCRIPTION
**Pull request by JesseGoodier**

### CODE REVIEW

**Comment by jessegoodier** [comment]
@chipzoller 
Do you know what version that fqdn PR needs?

I just made up a version here that is about a year old.

**Comment by chipzoller** [comment]
> Do you know what version that fqdn PR needs?

???

**Comment by jessegoodier** [comment]
if anyone know what version fixes this, I think that would be the check for this PR
```
Error: template: cost-analyzer/templates/cost-analyzer-frontend-config-map-template.yaml:57:52: executing "cost-analyzer/templates/cost-analyzer-frontend-config-map-template.yaml" at <.Values.kubecostFrontend.api.fqdn>: nil pointer evaluating interface {}.fqdn
```

**Comment by chipzoller** [comment]
It'll be pre-3.10

**Comment by jessegoodier** [comment]
@chipzoller 
you good with this version check? I'll own the code change.

**Comment by chipzoller** [comment]
This should be tested on CD applications first like Argo CD and Flux. Needs to be documented in the README clearly, and the PR template should be completed.

**Comment by jessegoodier** [comment]
> This should be tested on CD applications first like Argo CD and Flux. Needs to be documented in the README clearly, and the PR template should be completed.

really good point. Need to rethink this one.

**Comment by chipzoller** [comment]
It could still be viable, we would just have to wrap that cicd switch around this one as well or else it could hang up some folks.

**Pull request closed without merging**
