### PR TITLE
fix: nginx.conf for saml and oidc endpoints

### LINKED ISSUE #3172: [Bug] Secondaries Aggregator can't be turned off.
### Kubecost Helm Chart Version

v2.0.2 and v2.1.0 both

### Kubernetes Version

v1.27.7

### Kubernetes Platform

AKS

### Description

If I have `kubecostAggregator.enabled: false` and `kubecostAggregator.deployMethod: disabled` . The nginx.conf file fails to process successfully and thus keeps the frontend pod restarting.

The reason for nginx.conf not get parsed successfully is because upstream for aggregation is not defined due to disabling of aggregator but the endpoints in the conf file still tries to use it which nginx throws error saying [emer] aggregator host not defined in upstream.

I believe all those endpoints server should be configured based on the aggregator settings. Currently they are hardcoded expecting it to have aggregator running.

Example: https://github.com/kubecost/cost-analyzer-helm-chart/blob/v2.1.0/cost-analyzer/templates/cost-analyzer-frontend-config-map-template.yaml#L309

### Steps to reproduce

1. Disable aggregator and also make deployMethod as `disabled`.
2. Deploy the kubecost. The frontend pod will keep on restarting failing to parse the nginx.conf file.

### Expected behavior

I expect even if the aggregator is disabled everything else should work as is.

### Impact

We can't really use v2.x version.

### Screenshots

_No response_

### Logs

```Shell
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration                                                                                            │
│ /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/                                                                                                                   │
│ /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh                                                                                                       │
│ 10-listen-on-ipv6-by-default.sh: info: can not modify /etc/nginx/conf.d/default.conf (read-only file system?)                                                                               │
│ /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh                                                                                                               │
│ /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh                                                                                                           │
│ /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh                                                                                                           │
│ /docker-entrypoint.sh: Configuration complete; ready for start up                                                                                                                           │
│ 2024/02/23 00:21:55 [emerg] 1#1: host not found in upstream "aggregator" in /etc/nginx/conf.d/default.conf:94                                                                               │
│ nginx: [emerg] host not found in upstream "aggregator" in /etc/nginx/conf.d/default.conf:94
```

### Slack discussion

_No response_

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/ISSUE_GUIDELINES.md) and this is a bug impacting only the Helm chart.
- [X] I have searched other issues in this repository and mine is not recorded.

### PR DESCRIPTION
**Pull request by passionInfinite**
## What does this PR change?
This PR fixes the nginx.conf and includes the SAML, OIDC, login and logout endpoints conditional based on the required supplied values. This will help to fix #3172  as those nginx locations doesn't look for aggregator upstream hosts. The SAML, OIDC, Login and Logout endpoints are only supported for Federated Kubecost UI so technically this condition will help achieve those nginx locations.

## Does this PR rely on any other PRs?

Not at the moment.

## How does this PR impact users? (This is the kind of thing that goes in release notes!)

All the users using v2.x.x will be able to use Kubecost without enabling aggregator in the secondaries. This is same issue for v2.1.0 and gets fixed for that version as well.

## Links to Issues or tickets this PR addresses or fixes

#3172 

## What risks are associated with merging this PR? What is required to fully test this PR?

Tested using the `helm template` function by supplying the below values and saw the output template for nginx configmap if resolving correctly or not.

values supplied:

```
clusterController:
  enabled: true

federatedETL:
  agentOnly: false
  federatedCluster: true

kubecostAggregator:
  enabled: false
  deployMethod: 'disabled'

kubecostFrontend:
  enabled: true
```

The resolved templates looks like below:

```
---
# Source: cost-analyzer/templates/cost-analyzer-frontend-config-map-template.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: default
  labels:
    
    app.kubernetes.io/name: cost-analyzer
    helm.sh/chart: cost-analyzer-2.0.0
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app: cost-analyzer
data:
  nginx.conf: |
    gzip_static  on;

    # Enable gzip encoding for content of the provided types of 50kb and higher.
    gzip on;
    gzip_min_length 50000;
    gzip_proxied expired no-cache no-store private auth;
    gzip_types
        application/atom+xml
        application/geo+json
        application/javascript
        application/x-javascript
        application/json
        application/ld+json
        application/manifest+json
        application/rdf+xml
        application/rss+xml
        application/vnd.ms-fontobject
        application/wasm
        application/x-web-app-manifest+json
        application/xhtml+xml
        application/xml
        font/eot
        font/otf
        font/ttf
        image/bmp
        image/svg+xml
        text/cache-manifest
        text/calendar
        text/css
        text/javascript
        text/markdown
        text/plain
        text/xml
        text/x-component
        text/x-cross-domain-policy;

    upstream api {
        server release-name-cost-analyzer.default:9001;
    }

    upstream model {
        server release-name-cost-analyzer.default:9003;
    }
    upstream clustercontroller {
        server release-name-cluster-controller-service.default:9731;
    }
    upstream grafana {
        server release-name-grafana.default;
    }
    upstream forecasting {
        server release-name-forecasting.default:5000;
    }

    server {
        server_name _;
        root /var/www;
        index index.html;

        add_header Cache-Control "must-revalidate";
        large_client_header_buffers 4 32k;

        error_page 504 /custom_504.html;
        location = /custom_504.html {
            internal;
        }
        add_header Cache-Control "max-age=300";
        location / {
            try_files $uri $uri/ /index.html;
        }
        add_header ETag "2.0.0";
        listen 9090;
        listen [::]:9090;
        location /api/ {
            proxy_pass http://api/;
            proxy_redirect off;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_set_header  X-Real-IP  $remote_addr;
            proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        location /model/ {
            proxy_connect_timeout       300;
            proxy_send_timeout          300;
            proxy_read_timeout          300;
            proxy_pass http://model/;
            proxy_redirect off;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_set_header  X-Real-IP  $remote_addr;
            proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location ~ ^/(turndown|cluster)/ {

            add_header 'Access-Control-Allow-Origin' '*' always;
            add_header 'Access-Control-Allow-Methods' 'GET, PUT, POST, DELETE, OPTIONS' always;

            rewrite ^/(?:turndown|cluster)/(.*)$ /$1 break;
            proxy_pass http://clustercontroller;
            proxy_connect_timeout       180;
            proxy_send_timeout          180;
            proxy_read_timeout          180;
            proxy_redirect off;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_set_header X-Real-IP  $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        location /grafana/ {
            proxy_pass http://grafana/;
            proxy_redirect off;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_set_header  X-Real-IP  $remote_addr;
            proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $http_host;
        }
    
        location = /model/hideOrphanedResources {
            default_type 'application/json';
            add_header 'Access-Control-Allow-Origin' '*' always;
            add_header 'Access-Control-Allow-Methods' 'GET, PUT, POST, DELETE, OPTIONS' always;
            return 200 '{"hideOrphanedResources": "false"}';
        }
        location = /model/hideDiagnostics {
            default_type 'application/json';
            add_header 'Access-Control-Allow-Origin' '*' always;
            add_header 'Access-Control-Allow-Methods' 'GET, PUT, POST, DELETE, OPTIONS' always;
            return 200 '{"hideDiagnostics": "false"}';
        }

        location /model/multi-cluster-diagnostics-enabled {
            default_type 'application/json';
            add_header 'Access-Control-Allow-Origin' '*' always;
            add_header 'Access-Control-Allow-Methods' 'GET, PUT, POST, DELETE, OPTIONS' always;
            return 200 '{"multiClusterDiagnosticsEnabled": false}';
        }

        location /model/aggregatorEnabled {
            default_type 'application/json';
            return 200 '{"aggregatorEnabled": "true"}';
        }
        location /forecasting {
            default_type 'application/json';
            add_header 'Access-Control-Allow-Origin' '*' always;
            add_header 'Access-Control-Allow-Methods' 'GET, PUT, POST, DELETE, OPTIONS' always;
            proxy_read_timeout          300;
            proxy_pass http://forecasting/;
            proxy_redirect off;
            proxy_set_header Connection "";
            proxy_set_header  X-Real-IP  $remote_addr;
            proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        location /model/productConfigs {
            default_type 'application/json';
            add_header 'Access-Control-Allow-Origin' '*' always;
            add_header 'Access-Control-Allow-Methods' 'GET, PUT, POST, DELETE, OPTIONS' always;
            return 200 '\n
                {
                "ssoConfigured": "false",
                "dataBackupConfigured": "false"
                }
            ';
        }
    }

```

## How was this PR tested?

Using same process as above: `helm template cost-analyzer/ --values values.yaml` (values.yaml as shown above)

## Have you made an update to documentation? If so, please provide the corresponding PR.

No need for any documentation changes as far as i know.

### CODE REVIEW

**Comment by ghost** [comment]
Hi @passionInfinite thank you for the contribution! 

I reviewed the PR, in my testing, the yaml file that was rendered was still spitting out the following values:

```
location /oidc/ {
            proxy_connect_timeout       180;
            proxy_send_timeout          180;
            proxy_read_timeout          180;
            proxy_pass http://aggregator/oidc/;
            proxy_redirect off;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_set_header  X-Real-IP  $remote_addr;
            proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        location /saml/ {
            proxy_connect_timeout       180;
            proxy_send_timeout          180;
            proxy_read_timeout          180;
            proxy_pass http://aggregator/saml/;
            proxy_redirect off;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_set_header  X-Real-IP  $remote_addr;
            proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        location /login {
            proxy_connect_timeout       180;
            proxy_send_timeout          180;
            proxy_read_timeout          180;
            proxy_pass http://aggregator/login;
            proxy_redirect off;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_set_header  X-Real-IP  $remote_addr;
            proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header  X-Original-URI $request_uri;
        }

        location /logout {
            proxy_connect_timeout       180;
            proxy_send_timeout          180;
            proxy_read_timeout          180;
            proxy_pass http://aggregator/logout;
            proxy_redirect off;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_set_header  X-Real-IP  $remote_addr;
            proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
        }

```

**Comment by passionInfinite** [comment]
> Hi @passionInfinite thank you for the contribution!
> 
> I reviewed the PR, in my testing, the yaml file that was rendered was still spitting out the following values:
> 
> ```
> location /oidc/ {
>             proxy_connect_timeout       180;
>             proxy_send_timeout          180;
>             proxy_read_timeout          180;
>             proxy_pass http://aggregator/oidc/;
>             proxy_redirect off;
>             proxy_http_version 1.1;
>             proxy_set_header Connection "";
>             proxy_set_header  X-Real-IP  $remote_addr;
>             proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
>         }
>         location /saml/ {
>             proxy_connect_timeout       180;
>             proxy_send_timeout          180;
>             proxy_read_timeout          180;
>             proxy_pass http://aggregator/saml/;
>             proxy_redirect off;
>             proxy_http_version 1.1;
>             proxy_set_header Connection "";
>             proxy_set_header  X-Real-IP  $remote_addr;
>             proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
>         }
>         location /login {
>             proxy_connect_timeout       180;
>             proxy_send_timeout          180;
>             proxy_read_timeout          180;
>             proxy_pass http://aggregator/login;
>             proxy_redirect off;
>             proxy_http_version 1.1;
>             proxy_set_header Connection "";
>             proxy_set_header  X-Real-IP  $remote_addr;
>             proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
>             proxy_set_header  X-Original-URI $request_uri;
>         }
> 
>         location /logout {
>             proxy_connect_timeout       180;
>             proxy_send_timeout          180;
>             proxy_read_timeout          180;
>             proxy_pass http://aggregator/logout;
>             proxy_redirect off;
>             proxy_http_version 1.1;
>             proxy_set_header Connection "";
>             proxy_set_header  X-Real-IP  $remote_addr;
>             proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
>         }
> ```

@williamkubecost  Can you please share what values you passed in?

**Comment by ghost** [comment]
Hi @passionInfinite , I tested two different ways. The first way was using the command with the sample values.yaml file you provided. The second way was by running the following command below.

```
helm template . \                                                                                           
  --set clusterController.enabled=true \
  --set federatedETL.agentOnly=false \
  --set federatedETL.federatedCluster=true \
  --set kubecostAggregator.enabled=false \
  --set kubecostAggregator.deployMethod='disabled' \
  --set kubecostFrontend.enabled=true > rendered.yaml
```

**Comment by passionInfinite** [comment]
@williamkubecost  When you run that command you are on this PR branch right? Just making sure because it is working for me as saml and oidc are not enabled by default.

**Comment by passionInfinite** [comment]
@williamkubecost  Currently it only checks for oidc and saml enabled flags. Do you think it should also have a check of `not ((kubecostAggregator.deployMethod == 'disabled')`

**Comment by ghost** [comment]
@passionInfinite strange i'm not able to get the same result when testing, i just re-cloned your environment to doublecheck and ran the helm values command once more. You're more than welcome to add that change and re-upload the changes and i'll test it again in my local environment!

**Comment by passionInfinite** [comment]
```
helm template cost-analyzer/ \                                                                                           
  --set clusterController.enabled=true \
  --set federatedETL.agentOnly=false \
  --set federatedETL.federatedCluster=true \
  --set kubecostAggregator.enabled=false \
  --set kubecostAggregator.deployMethod='disabled' \
  --set kubecostFrontend.enabled=true > rendered.yaml
```
@williamkubecost  Can you try running this one. I used the `cost-analyzer/` folder in the command.

**Comment by ghost** [comment]
Hi @passionInfinite, I was able to get this going and confirm that the aggregator endpoints disappear. I'll go ahead and approve this!

**Review by ghost — APPROVED** [review]
LGTM!

**Comment by thomasvn** [comment]
@passionInfinite I agree that we should only create Nginx routes to `/saml` and `/oidc` if it is enabled in the Helm configs. Thanks!

Is it possible though that a user performs the following configs on a secondary? Would that then be incompatible with this PR?

```yaml
saml:
  enabled: true
kubecostAggregator:
  deployMethod: 'disabled'
```

**Comment by passionInfinite** [comment]
@thomasvn  Yes you are absolutely correct about that case. I was thinking to add one more condition to check the aggregate deploy method as well. Because if user enables SAML/OIDC we expect aggregator should be running. Let me know your thoughts!

**Comment by thomasvn** [comment]
@passionInfinite Yes I think in addition to checking whether SAML and OIDC are enabled, we should be ensuring Aggregator is not disabled. Something like the following:

```
{{- if and (or .Values.saml.enabled .Values.oidc.enabled) (not (eq (include "aggregator.deployMethod" .) "disabled") }}
```

**Comment by passionInfinite** [comment]
> @passionInfinite Yes I think in addition to checking whether SAML and OIDC are enabled, we should be ensuring Aggregator is not disabled. Something like the following:
> 
> ```
> {{- if and (or .Values.saml.enabled .Values.oidc.enabled) (not (eq (include "aggregator.deployMethod" .) "disabled") }}
> ```
@thomasvn  @williamkubecost 
I just updated the PR with the change. I have made that if condition to be parent of SAML and OIDC endpoints so that it can be covered for both login endpoints as well as the saml/oidc endpoints.

**Comment by passionInfinite** [comment]
@thomasvn @williamkubecost  Looks like a client rate limit happened on chart for v1.20. Can you please re-try that job? I don't have permission to retry.

**Comment by chipzoller** [comment]
The failure is known. We're removing the 1.20 test.

**Review by thomasvn — APPROVED** [review]

**Comment by chipzoller** [comment]
Please label if cherry pick required.

**Pull request merged**
