### PR TITLE
revert back to 91d

### PR DESCRIPTION
**Pull request by JesseGoodier**
## What does this PR change?
Reverts https://github.com/kubecost/cost-analyzer-helm-chart/pull/3399

### CODE REVIEW

**Comment by thomasvn** [comment]
Ok this looks good. Notably, this PR changes two things:

1. Do not set Aggregator's environment variables via the `.Values.kubecostModel.etlDailyStoreDurationDays` config. If you want to change Aggregator's `ETL_DAILY_STORE_DURATION_DAYS` which determines database ingestion/retention, that should live as its own config. More documentation [here](https://docs.kubecost.com/install-and-configure/install/multi-cluster/federated-etl/aggregator).
4. Reduce `etlDailyStoreDurationDays` default from `731` back to `91`. Additionally this variable now only has effect on the `costmodel` container and `cloudcost` container, and it determines how far back to query data and build ETL.

**Comment by thomasvn** [comment]
FYI. This has an effect on PR https://github.com/kubecost/cost-analyzer-helm-chart/pull/3415. The following config is no longer representative of what the Aggregator has configured for ingestion/retention.

```yaml
kubecostModel:
  etlDailyStoreDurationDays: ""
```

**Comment by jessegoodier** [comment]
> FYI. This has an effect on PR #3415. The following config is no longer representative of what the Aggregator has configured for ingestion/retention.
> 
> ```yaml
> kubecostModel:
>   etlDailyStoreDurationDays: ""
> ```

we aren't using that yet. really was for the hourly store disabling concern.

**Review by thomasvn — APPROVED** [review]

**Pull request merged**
