### PR TITLE
Delete requirements.yaml and edit helm templates

### PR DESCRIPTION
**Pull request by calvinwang**
Description: delete requirements.yaml, update thanos, prometheus, and grafana subchart templates

Testing:
- deleted kubecost requirements.yaml
- set global thanos/prometheus/grafana enabled flag set to true/false
- reinstalled kubecost in a new namespace
- checked `kubectl get pods`, `kubectl get deployments`, `kubectl get services` for the subchart associated templates

### CODE REVIEW

**Comment by dwbrown2** [comment]
@AjayTripathy @itscalvinwang does this break helm 2?

**Comment by dwbrown2** [comment]
Is this PR still marked as "do not merge?"

**Comment by AjayTripathy** [comment]
No, I am testing this and we can remove it. May break helm2 users though.

On Fri Jun 25, 2021, 10:57 PM GMT, Webb Brown ***@***.***>
wrote:

Is this PR still marked as "do not merge?"

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubecost/cost-analyzer-helm-chart/pull/694#issuecomment-868872116>,
or unsubscribe

**Review by mbolt35 — APPROVED** [review]
RIP Postgres - LGTM

**Comment by mbolt35** [comment]
Tested with: 
```
Client: &version.Version{SemVer:"v2.16.5", GitCommit:"89bd14c1541fa93a09492010030fd3699ca65a97", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.5", GitCommit:"89bd14c1541fa93a09492010030fd3699ca65a97", GitTreeState:"clean"}
```

Works fine.

**Pull request merged**
