### PR TITLE
add PSP failure message

### PR DESCRIPTION
**Pull request by chipzoller**
Signed-off-by: chipzoller <chipzoller@gmail.com>

## What does this PR change?

Adds a failure message when PSPs are enabled.

## Does this PR rely on any other PRs?

2.0 changes only

## How does this PR impact users? (This is the kind of thing that goes in release notes!)

Fails the installation/upgrade if PSPs are enabled.

## How was this PR tested?

In a local 1.24 cluster with PSPs enabled as well as a standard upgrade where no PSPs are enabled.

### CODE REVIEW

**Comment by chipzoller** [comment]
Note that CI will fail because the state of the chart on this branch requires changes past 1.108 which is what it references.

**Review by JesseGoodier — APPROVED** [review]
I like this for two reasons.
1. simplification
2. makes it obvious that there is a need to consider the impact of leaving PSP enabled now that it isn't supported in most current k8s versions.

**Comment by chipzoller** [comment]
Thanks, @jessegoodier. Although this is minor, @thomasvn and @AjayTripathy, are you satisfied with this approach?

**Comment by thomasvn** [comment]
Looks good! This should cover cases where users are deploying Kubecost-related PSPs. What if users are deploying PSPs in the subcharts? Do we need to capture that in the `if` statement here too?

**Pull request merged**
