### PR TITLE
provide reasonable default for db copy chunks

### PR DESCRIPTION
**Pull request by ameijer**
## What does this PR change?
Provides a 'middle ground' setting in the time vs resources tradeoff for the db copy operation 

## Does this PR rely on any other PRs?
no

## How does this PR impact users? (This is the kind of thing that goes in release notes!)
it will make new data show up in kubecost UI sooner, while keeping ram usage reasonable

## How was this PR tested?
tested via chart template rendering

### CODE REVIEW

**Comment by chipzoller** [comment]
CI is going to fail here because `cost-model-nightly` issues, FYI.

**Review by michaelmdresser — APPROVED** [review]
Perfect. Great documentation.

**Comment by michaelmdresser** [comment]
This is a major UX improvement, I think its worth picking into 2.1

**Pull request merged**
