### PR TITLE
Adds consistency around how we are templating `.Values.global.additionalLabels`

### PR DESCRIPTION
**Pull request by thomasvn**
## What does this PR change?

Templates `.Values.global.additionalLabels` on all Deployments, Statefulsets, Daemonsets, and their pod templates. Previously, it was missing in some of these manifests. Or it was only being applied in the Pod template labels and not the Deployment labels. Or vice versa.

I'm open to feedback as to whether this is the right approach or not. The Helm configuration itself is vague, so I've included a comment stating what it now intends to do.

## Does this PR rely on any other PRs?

N/A

## How does this PR impact users? (This is the kind of thing that goes in release notes!)

Previously `.Values.global.additionalLabels` was inconsistent in how it would apply these additional labels to specific manifests. Although we are now being consistent in templating, this is a potential breaking change for users whose configs only worked in the previous inconsistent templating

## Links to Issues or tickets this PR addresses or fixes

N/A

## What risks are associated with merging this PR? What is required to fully test this PR?

Risks stated above.

## How was this PR tested?

```yaml
# values.yaml
global:
  additionalLabels:
    owner: thomasn
```

```sh
helm template cost-analyzer -f values.yaml | less
```

Validated that I could see the `owner: thomasn` label in all Deployments (and their pod templates) created.

## Have you made an update to documentation? If so, please provide the corresponding PR.

Documentation in `values.yaml`.

### CODE REVIEW

**Comment by thomasvn** [comment]
@chipzoller Let me know if you have any thoughts on this from a UX perspective!

**Comment by chipzoller** [comment]
I haven't inspected the contents of this change, but saying "global" means to truly apply to everything. To not have done so seems like obvious oversights to me. If this change makes "global" apply to everything then that's correct.

**Comment by jessegoodier** [comment]
> I haven't inspected the contents of this change, but saying "global" means to truly apply to everything. To not have done so seems like obvious oversights to me. If this change makes "global" apply to everything then that's correct.

which pods are missing?

**Comment by jessegoodier** [comment]
I'll test this, and fix the merge for something that will conflict.

**Comment by chipzoller** [comment]
> > I haven't inspected the contents of this change, but saying "global" means to truly apply to everything. To not have done so seems like obvious oversights to me. If this change makes "global" apply to everything then that's correct.
> 
> which pods are missing?

Don't know personally.

**Review by JesseGoodier — APPROVED** [review]
Tested, works!

**Comment by thomasvn** [comment]
I've tested as well. For now, it's documented that we are only adding labels to Deployments, Statefulsets, Daemonsets, and their pod templates. In the future, we may need to add the labels to other resources such as Services, Ingresses, ServiceAccounts, etc.

**Pull request merged**
