### PR TITLE
support nodeselectors throughout

### PR DESCRIPTION
**Pull request by AjayTripathy**

### CODE REVIEW

**Review by mbolt35 — APPROVED** [review]
LGTM

**Comment by kesor** [comment]
@AjayTripathy This created a problem for us since we want kubecost to run on specific nodes, but the network daemonset must not use the same selector as the model.

**Comment by AjayTripathy** [comment]
@kesor thanks for the feedback. We'll create a seperate nodeselector for that daemonset.

**Comment by AjayTripathy** [comment]
I've filed #772 to address- meanwhile can you use the old method of taints/tolerations for this to work?

**Comment by kesor** [comment]
> I've filed #772 to address- meanwhile can you use the old method of taints/tolerations for this to work?

meanwhile I removed the `nodeSelector` for network analyzer

**Pull request merged**
