### PR TITLE
feat: create checksum for configmaps and secrets to enforce restart w…

### LINKED ISSUE #3403: [Feature] replace helm-rollout-restarter method with helm best practice to restart pods on configmap changes
### Problem Statement

pods should get restarted during deployment when configmaps change. However, the current approach with "helm-rollout-restarter" always restarts the pods when "helm template" is running which results in a restart whenever argocd recognizes git commits in the gitops repo. There is a feature to disable helm-rollout-restarter introduced with https://github.com/kubecost/cost-analyzer-helm-chart/pull/3324. however, then pods never ever get restarted when configmaps change.

### Solution Description

Use the helm best practice https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments which is also used in loki: https://github.com/grafana/loki/blob/5ada92b190c671055bb09ca2dd234b6bac49289e/production/helm/loki/templates/admin-api/deployment-admin-api.yaml#L35

### Alternatives

_No response_

### Additional Context

_No response_

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/ISSUE_GUIDELINES.md) and this is a feature request only for the Helm chart.
- [X] I have searched other issues in this repository and mine is not recorded.

### PR DESCRIPTION
**Pull request by jkleinlercher**
…hen really needed in a gitops friendly way

## What does this PR change?

with this PR deployments where "helm-rollout-restarter" annotation or label is used, I introduced a checksum of rendered configmaps and secrets. the configmaps and secrets which are honored are listed in the _helpers.tpl function configsChecksum. So this list needs to be maintained.

## How does this PR impact users? (This is the kind of thing that goes in release notes!)

with this PR pods get restarted also when cicd is set to true

## Links to Issues or tickets this PR addresses or fixes

fixes https://github.com/kubecost/cost-analyzer-helm-chart/issues/3403

## How was this PR tested?

```
helm template . |grep checksum
        checksum/configs: df0658db2eb919288b37b12dc7dde460d4d19890c81e085c945f39c468d33256
        checksum/configs: df0658db2eb919288b37b12dc7dde460d4d19890c81e085c945f39c468d33256

helm template . --set kubecostToken=blub | grep checksum
        checksum/configs: b472370c2d05a1e7b3dabf7b269fddb5722c91b90d63fa1a9d253ac89793e52e
        checksum/configs: b472370c2d05a1e7b3dabf7b269fddb5722c91b90d63fa1a9d253ac89793e52e
```

## Have you made an update to documentation? If so, please provide the corresponding PR.

no

### CODE REVIEW

**Comment by jessegoodier** [comment]
This is awesome! 
I won't have time to test before our 2.3.0 GA, but I think we can get this in .1 or .2 
Thank you for doing this!

**Comment by jessegoodier** [comment]
@jkleinlercher did you close this due to an issue?
I had been waiting for GA of 2.3, which I hope will be this week.

Would love to this this in!

**Comment by jkleinlercher** [comment]
Oh no I unintentionally deleted my fork, that’s why this issue got closed. I need to figure out how I can recreate my fork. Sorry!!

**Comment by jkleinlercher** [comment]
@jessegoodier I created a new PR https://github.com/kubecost/cost-analyzer-helm-chart/pull/3459 for this. sorry for any inconvenience

**Pull request closed without merging**
