### PR TITLE
Aggregator Settings Endpoints

### PR DESCRIPTION
**Pull request by nik-kc**
## What does this PR change?
* KC settings endpoints will be now resolved by Aggregator.

## Does this PR rely on any other PRs?
* [Indeed it does](https://github.com/kubecost/kubecost-cost-model/pull/2268). Note, the helm PR won't pass tests until the KCM PR is merged.

## How does this PR impact users? (This is the kind of thing that goes in release notes!)
* KC settings endpoints will be now resolved by Aggregator.

## Links to Issues or tickets this PR addresses or fixes
* Closes [GTM-322](https://kubecost.atlassian.net/browse/SELFHOST-322).

## How was this PR tested?
* Tested in the `nik` namespace in `dev-1`:
  * Validated that all endpoints route as expected.
  * Validated that the [basic health test](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/templates/tests/basic-health.yaml) passes.

### CODE REVIEW

**Comment by nik-kc** [comment]
@chipzoller Could I request your help here? I'm seeing failures while running [this test](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/templates/tests/basic-health.yaml#L36-L48), which calls an endpoint that this PR moves to Aggregator. Unfortunately, the CI logs don't seem to show the output of the test, so I don't what status code it's getting back.

My first thought was to change the [wait for ready](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/.github/workflows/chart.yaml#L110C99-L110C112) to wait on Aggregator, but GitHub Actions seems to be ignoring that change. I'm assuming the workflow changes only have an effect in `develop`?

**Comment by chipzoller** [comment]
Any changes that need to happen in CI need to be in a separate PR because of current token configurations. Does something actually need to change in CI though?

**Comment by chipzoller** [comment]
What's happening here is that the Helm test is failing:

```
pod basic-health failed
```

**Comment by nik-kc** [comment]
That's correct, that basic health test is failing. I don't know why it's failing, because the CI logs don't show the output from the test, only that it had an exit code of 1. My assumption is that we need to update the [wait for ready](https://github.com/kubecost/cost-analyzer-helm-chart/pull/3177/files#diff-b4e327c49c11f0d80b3a8c30f79ccc0a972f3cf626b872a8775c9395e840aca6R110) step to wait for Aggregator, not cost-model. This is why I believe we may need to update CI.

**Comment by chipzoller** [comment]
You can test this yourself. Simply deploy the chart based on the changes here and run `helm test` on the release. The test Pod will run and provide output in Pod logs.

**Comment by nik-kc** [comment]
@chipzoller I tested myself as you described, and the test passed. I also confirmed that the changes I made in KCM and the helm chart were present in my deployment.

Any thoughts on why the tests are failing in GH Actions?

**Comment by chipzoller** [comment]
I tested this PR just as it was tested in CI and I got the same failure. The tester Pod fails with the following output:

```
# k -n kubecost logs basic-health
Getting current Kubecost state.
jq: error (at <stdin>:1): Cannot index number with string "code"
parse error: Invalid numeric literal at line 1, column 9
sh: out of range
Failed to fetch Kubecost configuration. Response was 404 page not found
```

The test relies on the ability to get the working configuration from `/model/getConfigs` and I see this PR has changed that [here](https://github.com/kubecost/cost-analyzer-helm-chart/pull/3177/files#diff-f6d5a9ddec47ad0c6043e1a7258057f261cc6a135446693326d5cd4d27fc1497R1018-R1025). A `200` response indicates success and everything else indicates failure. This is how Kubecost has behaved since 1.x.

**Comment by nik-kc** [comment]
I will admit that, after a night of much needed brain-sleep, I've realized that _of course_ this repo isn't going to pull the image from my branch of KCM, so _of course_ these tests are going to fail.

I need to get my KCM PR merged before this PR can be tested.

**Comment by chipzoller** [comment]
Ah ok. Let's set this to draft then. I also didn't check the relevant section in the PR template so my fault on that one.

**Pull request closed without merging**
