### PR TITLE
Add ability to set `containerSecurityContext` for Grafana and override `securityContext` for cost-analyzer

### PR DESCRIPTION
**Pull request by JorisAndrade**
## What does this PR change?

- This PR adds missing `containerSecurityContext` to Grafana 
- It also the ability to overrides properties of the default `securityContext` for the `cost-analyzer`

## How does this PR impact users? (This is the kind of thing that goes in release notes!)

Add ability to set `containerSecurityContext` for Grafana and override `securityContext` for the `cost-analyzer`

## How was this PR tested?

```
$ helm template --set 'grafana.containerSecurityContext.allowPrivilegeEscalation=false' cost-analyzer --show-only charts/grafana/templates/deployment.yaml | yq '.spec.template.spec.containers.[].securityContext'
allowPrivilegeEscalation: false
allowPrivilegeEscalation: false
```

```
$ helm template cost-analyzer --show-only charts/grafana/templates/deployment.yaml | yq '.spec.template.spec.containers.[].securityContext'
null
null
```

```
$ helm template cost-analyzer --show-only templates/cost-analyzer-deployment-template.yaml | yq '.spec.template.spec.securityContext'

fsGroup: 1001
runAsGroup: 1001
runAsUser: 1001
```

```
$ helm template --set 'global.securityContext.runAsNonRoot=true' cost-analyzer --show-only templates/cost-analyzer-deployment-template.yaml | yq '.spec.template.spec.securityContext'

fsGroup: 1001
runAsGroup: 1001
runAsNonRoot: true
runAsUser: 1001
```

```
$ helm template --set 'global.securityContext.runAsUser=2001' cost-analyzer --show-only templates/cost-analyzer-deployment-template.yaml | yq '.spec.template.spec.securityContext'

fsGroup: 1001
runAsGroup: 1001
runAsUser: 2001
```

## Have you made an update to documentation?

Yes!

### CODE REVIEW

**Comment by jessegoodier** [comment]
Nice work!
We are actually in the process of adding pod/container security contexts to make all pods run as nonRoot by default.

Do you think that a global section for this would work for your use case? 

like this, with templating in all pods:
```
global:
  securityContext:
    fsGroup: 65534
    runAsGroup: 65534
    runAsNonRoot: true
    runAsUser: 65534
    seccompProfile:
      type: RuntimeDefault
  containerSecurityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop:
      - ALL
```

**Comment by JorisAndrade** [comment]
This would work yeah! As long as we can overload to put what we need (like seccomp in our case)

**Comment by JorisAndrade** [comment]
> Nice work! We are actually in the process of adding pod/container security contexts to make all pods run as nonRoot by default.
> 
> Do you think that a global section for this would work for your use case?
> 
> like this, with templating in all pods:
> 
> ```
> global:
>   securityContext:
>     fsGroup: 65534
>     runAsGroup: 65534
>     runAsNonRoot: true
>     runAsUser: 65534
>     seccompProfile:
>       type: RuntimeDefault
>   containerSecurityContext:
>     allowPrivilegeEscalation: false
>     readOnlyRootFilesystem: true
>     capabilities:
>       drop:
>       - ALL
> ```

Do you have any ETA on this? Would like to avoid having to keep a fork on our side

**Comment by jessegoodier** [comment]
We are attempting to get this in 1.106. Would love your feedback on:

https://github.com/kubecost/cost-analyzer-helm-chart/pull/2493

and if this would fit your needs.

**Pull request closed without merging**
