### PR TITLE
Ajay tripathy fix imagepullsecrets

### PR DESCRIPTION
**Pull request by AjayTripathy**
## What does this PR change?
Fix for regression reported in #1359 and introduced in #1330 

## Does this PR rely on any other PRs?
No

## How does this PR impact users? (This is the kind of thing that goes in release notes!)
Fix an assortment of config options accidentally removed when the cost-analyzer-server pod was removed

## Links to Issues or ZD tickets this PR addresses or fixes
https://github.com/kubecost/cost-analyzer-helm-chart/issues/1359

## How was this PR tested?
Added some tolerations and observed:
```
        tolerations:
        - effect: NoSchedule
          key: foobarbaz
          operator: Equal
          value: value
```

## Have you made an update to documentation?
No-- this is fixing a regression in intended behavior.

### CODE REVIEW

**Comment by michaelmdresser** [comment]
Hey, just a heads up -- this branch's Git history looks pretty wild.

**Comment by AjayTripathy** [comment]
> Hey, just a heads up -- this branch's Git history looks pretty wild.

Yeah... not sure what happened? the diff looks really straightforward?

**Review by biancaburtoiu — APPROVED** [review]

**Comment by nikovacevic** [comment]
I think @michaelmdresser is right to point out that, even though the diff in this particular GH view looks simple enough, the ability to go back in git history and understand what we patched here is obscured.

@AjayTripathy ideally, can we try to get to a place where git history looks a little cleaner for these release branch patches? (And just in general -- I don't know if a similar thing occurred merging these changes into `develop`.) Happy to set up a quick time to chat about how we can make the process smoother and simpler.

**Comment by michaelmdresser** [comment]
Separately from the git concerns, is there a sister PR for this one that goes into `develop`?

**Comment by AjayTripathy** [comment]
No...looks like I forgot to cherry pick against develop. Will do so now.

**Pull request merged**
