### PR TITLE
Changes to add security context for cloud-cost

### PR DESCRIPTION
**Pull request by mclean0328**
## What does this PR change?
Adds security context values for cloud-costs when openshift is enabled

## Does this PR rely on any other PRs?
No

## How does this PR impact users? (This is the kind of thing that goes in release notes!)
Only users deploying to OpenShift 

## How was this PR tested?
Helm templates

## Have you made an update to documentation? If so, please provide the corresponding PR.
No

### CODE REVIEW

**Comment by thomasvn** [comment]
Awesome thanks @mclean0328. Could you quickly document in this PR what `helm template` command you ran? And the successful result you received on the cloud-cost deployment?

**Comment by thomasvn** [comment]
Also, it should be noted that this PR will affect _all_ users of the Cloud Cost pod in this upcoming release, as the new default securityContext we're applying is:

```yaml
  spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
```

Therefore it may also be worthwhile quickly deploying the pod and ensuring CloudCosts correctly runs against AWS, Azure, GCP.

**Comment by jessegoodier** [comment]
> Also, it should be noted that this PR will affect _all_ users of the Cloud Cost pod in this upcoming release, as the new default securityContext we're applying is:
> 
> ```yaml
>   spec:
>       securityContext:
>         runAsUser: 1001
>         runAsGroup: 1001
>         fsGroup: 1001
> ```
> 
> Therefore it may also be worthwhile quickly deploying the pod and ensuring CloudCosts correctly runs against AWS, Azure, GCP.

seems reasonable. 1001 is our default user. simple note good enough?

**Comment by mclean0328** [comment]
I was able to test of Azure and everything came up and the cloud-cost pod came up and cloud integration worked correctly.

**Review by JesseGoodier — APPROVED** [review]

**Pull request merged**
