### PR TITLE
[SELFHOST-1141] Atm/selfhost 1141 yaml actions

### PR DESCRIPTION
**Pull request by ameijer**
## What does this PR change?
adds ability to config actiona via yaml

## Does this PR rely on any other PRs?
https://github.com/kubecost/cluster-controller/pull/63

## How does this PR impact users? (This is the kind of thing that goes in release notes!)
provides a way for users to configure actions via yaml

## Links to Issues or tickets this PR addresses or fixes
https://kubecost.atlassian.net/browse/SELFHOST-1141

## How was this PR tested?
tested in isolated cluster, confirmed configurated actions showed up on boot 

## Have you made an update to documentation? If so, please provide the corresponding PR.
has commented out values

### CODE REVIEW

**Review by teevans — APPROVED** [review]
YESSSSS

**Review by chipzoller — CHANGES_REQUESTED** [review]
Please add field descriptions

**Comment by ameijer** [comment]
@chipzoller added links to the docs pages, which would likely do a better job than I ever could :)

**Review by chipzoller — APPROVED** [review]
Please add labels if this needs to be cherry picked.

**Comment by chipzoller** [comment]
If this needs to be cherry picked, please use a label to indicate target branch.

**Comment by ameijer** [comment]
thanks chip, added

**Pull request merged**
