### PR TITLE
Prometheus Alertmanager ConfigmapReload disabled by default

### PR DESCRIPTION
**Pull request by thomasvn**
## What does this PR change?

- Default disable Prometheus's Alertmanager ConfigmapReload container.
- Fix the arguments being passed to Alertmanager ConfigmapReload. Big thanks to @chipzoller!

Originally, the issue was that the new `quay.io/prometheus-operator/prometheus-config-reloader` image was failing to start because it was being passed incorrect parameters.

```
$ kubectl describe pod thomasn-alerts-prometheus-alertmanager-544d587f9b-xlx77

Events:
  Type     Reason     Age               From               Message
  ----     ------     ----              ----               -------
  Normal   Scheduled  26s               default-scheduler  Successfully assigned thomasn-alerts/thomasn-alerts-prometheus-alertmanager-544d587f9b-xlx77 to gke-qa-gcp1-default-pool-169fb9bb-sock
  Normal   Pulled     23s               kubelet            Container image "quay.io/prometheus/alertmanager:v0.25.0" already present on machine
  Normal   Created    23s               kubelet            Created container prometheus-alertmanager
  Normal   Started    23s               kubelet            Started container prometheus-alertmanager
  Normal   Pulled     7s (x3 over 23s)  kubelet            Container image "quay.io/prometheus-operator/prometheus-config-reloader:v0.68.0" already present on machine
  Normal   Created    7s (x3 over 23s)  kubelet            Created container prometheus-alertmanager-configmap-reload
  Normal   Started    7s (x3 over 22s)  kubelet            Started container prometheus-alertmanager-configmap-reload
  Warning  BackOff    5s (x3 over 20s)  kubelet            Back-off restarting failed container prometheus-alertmanager-configmap-reload in pod thomasn-alerts-prometheus-alertmanager-544d587f9b-xlx77_thomasn-alerts(ffc5cec8-7511-4807-97b4-82958d3161b6)
```

```
$ kubectl logs thomasn-alerts-prometheus-alertmanager-544d587f9b-xlx77 -c prometheus-alertmanager-configmap-reload

unknown long flag '--volume-dir'
```

## Does this PR rely on any other PRs?

- No

## How does this PR impact users? (This is the kind of thing that goes in release notes!)

- Affects users deploying Prometheus Alertmanager via the cost-analyzer-helm-chart. However, I suspect there are few.
- For those users, the ConfigmapReloader will be default disabled. When they update their alerting configs in the configmap, it will require a hard restart of the Alertmanager pod.

## Links to Issues or tickets this PR addresses or fixes

- Fixes small bug originally introduced in PR https://github.com/kubecost/cost-analyzer-helm-chart/pull/2698

## What risks are associated with merging this PR? What is required to fully test this PR?

- Minor risks to existing users deploying Prometheus Alertmanager via the cost-analyzer-helm-chart

## How was this PR tested?

Now seeing successful logs from the `prometheus-alertmanager-configmap-reload` container

```
level=info ts=2023-11-16T21:22:50.099152251Z caller=main.go:115 msg="Starting prometheus-config-reloader" version="(version=0.68.0, branch=refs/tags/v0.68.0, revision=52526e3b0cfb5f3deaa967998ff88
level=info ts=2023-11-16T21:22:50.099323059Z caller=main.go:116 build_context="(go=go1.20.7, platform=linux/amd64, user=Action-Run-ID-6123005285, date=20230908-14:54:18, tags=unknown)"
level=info ts=2023-11-16T21:22:50.105095687Z caller=reloader.go:237 msg="started watching config file and directories for changes" cfg= out= dirs=/etc/config
```

## Have you made an update to documentation? If so, please provide the corresponding PR.

- Not needed.

### CODE REVIEW

**Comment by chipzoller** [comment]
Under what situation are you finding this doesn't work? It was tested, the container started, and that log message was not found.

**Comment by thomasvn** [comment]
The new `quay.io/prometheus-operator/prometheus-config-reloader` image is correctly working as a sidecar container for the `prometheus-server` pod. And I believe this is what we tested in PR https://github.com/kubecost/cost-analyzer-helm-chart/pull/2698

But it doesn't seem to work with the `prometheus-alertmanager` pod. The change was made [here](https://github.com/kubecost/cost-analyzer-helm-chart/pull/2698/files#diff-1fface9fcabec841ba2f05e211794e2f074ecf0ca1190f860bdf1a23f17d3b9eR351-R364). I'd say not urgent because alertmanager is [off by default](https://github.com/kubecost/cost-analyzer-helm-chart/blob/287ca76657f9f4130b0a25e06e87aac624cb93d3/cost-analyzer/values.yaml#L136-L138), and I'm not aware of many users deploying it.

**Comment by chipzoller** [comment]
Ok, this was my fault. Let's fix the problem though even if we do disable it by default. I've pushed a fix which updates the remainder of the args that didn't get updated. Have a look.

**Comment by thomasvn** [comment]
@chipzoller Great find & fix! Much better than the temporary workaround I initially proposed. I'll quickly test this.

**Comment by thomasvn** [comment]
Tested, and seeing successful logs!

**Review by chipzoller — APPROVED** [review]
Do we want this in 107 or keep in develop?

**Comment by thomasvn** [comment]
I think keeping this PR in develop is ok. Tagging @jessegoodier & @cliffcolvin for awareness in case they believe it should go in v1.107.x.

**Pull request merged**
