### PR TITLE
Add support for thanos query url

### PR DESCRIPTION
**Pull request by vishesh92**

### CODE REVIEW

**Comment by AjayTripathy** [comment]
Hi @vishesh92, can you help us understand what you are trying to do here? We don't offer support for durable storage in our free version, but our enterprise product does. There’s also a good bit of other configuration work needed to support Thanos, and querying against an arbitrary Thanos version may not work.

**Comment by vishesh92** [comment]
I thought this was available in free version as well. I was thinking of using my own thanos setup instead of the one setup by helm chart.

**Comment by dwbrown2** [comment]
Hi @vishesh92 this unfortunately isn't supported in our free version. Want to send an email to team@kubecost.com to see if there's another way to support your needs?

**Comment by dwbrown2** [comment]
Hi @vishesh92, would you want to discuss different paths forward?

**Comment by dwbrown2** [comment]
Closing now due to inactivity. Let me know if you would like to discuss.

**Pull request closed without merging**
