### PR TITLE
Added ability to add security context for cloud-costs container

### LINKED ISSUE #3187: [Feature] Missing SecurityContext for cloud-cost Container
### Problem Statement

If cloudCost is enabled there is no possibility to set the securityContext for the container.

### Solution Description

Expanding _helpers.tpl file with a section below line 1053 with something like:
  {{- if .Values.global.containerSecurityContext }}
  securityContext:
    {{- toYaml .Values.global.containerSecurityContext | nindent 4 }}
  {{- end }}

### Alternatives

_No response_

### Additional Context

_No response_

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/ISSUE_GUIDELINES.md) and this is a feature request only for the Helm chart.
- [X] I have searched other issues in this repository and mine is not recorded.

### PR DESCRIPTION
**Pull request by ghost**
## What does this PR change?
Adds ability to add security context for cloud-costs container. 

## Does this PR rely on any other PRs?
No.

## How does this PR impact users? (This is the kind of thing that goes in release notes!)
This was a feature request. 

## Links to Issues or tickets this PR addresses or fixes

https://github.com/kubecost/cost-analyzer-helm-chart/issues/3187

## What risks are associated with merging this PR? What is required to fully test this PR?
No risk, minimal impact.

## How was this PR tested?
Tested via the following command:
```
helm template cost-analyzer/ --values values-test.yaml > rendered.yaml
```
This is the values file I used:

```
cloudCost:
    # enabled: true # this logic is always enabled if cloud billing integration is configured. This option is no longer configurable.
    labelList:
      IsIncludeList: false
      # format labels as comma separated string (ex. "label1,label2,label3")
      labels: ""
    topNItems: 1000

global:
  containerSecurityContext:
    allowPrivilegeEscalation: true

```

## Have you made an update to documentation? If so, please provide the corresponding PR.
No.

### CODE REVIEW

**Comment by chipzoller** [comment]
Strange this fails on 1.20.

**Comment by chipzoller** [comment]
@williamkubecost, can you bring up a 1.20 KinD/K3d cluster and see why this fails to come up?

**Comment by ghost** [comment]
> @williamkubecost, can you bring up a 1.20 KinD/K3d cluster and see why this fails to come up?

So I was able to reproduce this on 1.20. It looks like it fails to fully come up due to some weird pod disruption issue:

```
W0301 16:02:26.240175       1 reflector.go:424] pkg/mod/k8s.io/client-go@v0.26.2/tools/cache/reflector.go:169: failed to list *v1.PodDisruptionBudget: the server could not find the requested resource
E0301 16:02:26.240219       1 reflector.go:140] pkg/mod/k8s.io/client-go@v0.26.2/tools/cache/reflector.go:169: Failed to watch *v1.PodDisruptionBudget: failed to list *v1.PodDisruptionBudget: the server could not find the requested resource
W0301 16:02:27.179890       1 reflector.go:424] pkg/mod/k8s.io/client-go@v0.26.2/tools/cache/reflector.go:169: failed to list *v1.PodDisruptionBudget: the server could not find the requested resource
E0301 16:02:27.179918       1 reflector.go:140] pkg/mod/k8s.io/client-go@v0.26.2/tools/cache/reflector.go:169: Failed to watch *v1.PodDisruptionBudget: failed to list *v1.PodDisruptionBudget: the server could not find the requested resource
W0301 16:02:29.765634       1 reflector.go:424] pkg/mod/k8s.io/client-go@v0.26.2/tools/cache/reflector.go:169: failed to list *v1.PodDisruptionBudget: the server could not find the requested resource
E0301 16:02:29.765658       1 reflector.go:140] pkg/mod/k8s.io/client-go@v0.26.2/tools/cache/reflector.go:169: Failed to watch *v1.PodDisruptionBudget: failed to list *v1.PodDisruptionBudget: the server could not find the requested resource
W0301 16:02:35.368044       1 reflector.go:424] pkg/mod/k8s.io/client-go@v0.26.2/tools/cache/reflector.go:169: failed to list *v1.PodDisruptionBudget: the server could not find the requested resource
E0301 16:02:35.368070       1 reflector.go:140] pkg/mod/k8s.io/client-go@v0.26.2/tools/cache/reflector.go:169: Failed to watch *v1.PodDisruptionBudget: failed to list *v1.PodDisruptionBudget: the server could not find the requested resource
W0301 16:02:44.954698       1 reflector.go:424] pkg/mod/k8s.io/client-go@v0.26.2/tools/cache/reflector.go:169: failed to list *v1.PodDisruptionBudget: the server could not find the requested resource
E0301 16:02:44.954721       1 reflector.go:140] pkg/mod/k8s.io/client-go@v0.26.2/tools/cache/reflector.go:169: Failed to watch *v1.PodDisruptionBudget: failed to list *v1.PodDisruptionBudget: the server could not find the requested resource
W0301 16:03:01.169176       1 reflector.go:424] pkg/mod/k8s.io/client-go@v0.26.2/tools/cache/reflector.go:169: failed to list *v1.PodDisruptionBudget: the server could not find the requested resource
E0301 16:03:01.169265       1 reflector.go:140] pkg/mod/k8s.io/client-go@v0.26.2/tools/cache/reflector.go:169: Failed to watch *v1.PodDisruptionBudget: failed to list *v1.PodDisruptionBudget: the server could not find the requested resource
W0301 16:03:42.320573       1 reflector.go:424] pkg/mod/k8s.io/client-go@v0.26.2/tools/cache/reflector.go:169: failed to list *v1.PodDisruptionBudget: the server could not find the requested resource
E0301 16:03:42.320720       1 reflector.go:140] pkg/mod/k8s.io/client-go@v0.26.2/tools/cache/reflector.go:169: Failed to watch *v1.PodDisruptionBudget: failed to list *v1.PodDisruptionBudget: the server could not find the requested resource

```

Though, i removed the security context from deployment and the deployment still failed to come up. Not sure if this a weird bug that was patched in newer Kubernetes version (given 1.20 is 4 years old at this point). But I was not able to reproduce this on any other versions. 

Thoughts on this @chipzoller ?

**Comment by chipzoller** [comment]
The policy/v1 API version wasn't available until 1.21, which is where the PodDisruptionBudget API resides. The watch is failing because that version doesn't exist in 1.20. I'm not sure why it's failing here given that no PDBs have been enabled in the default values file.

I think we can probably just remove the test for v1.20 in the CI matrix. Is that something you'd like to do? Should be a simple change but must be sent in a separate PR.

**Comment by ghost** [comment]
@chipzoller PR created to remove 1.20 from tests: https://github.com/kubecost/cost-analyzer-helm-chart/pull/3193

**Review by chipzoller — APPROVED** [review]

**Pull request merged**
