### PR TITLE
Add logging to readme

### PR DESCRIPTION
**Pull request by dramich**
## What does this PR change?
Add logging to readme

### CODE REVIEW

**Review by michaelmdresser — APPROVED** [review]

**Comment by dwbrown2** [comment]
Like the output but this doesn't feel like quite the right location for this...

**Comment by dwbrown2** [comment]
Maybe below the config options table?

**Comment by dramich** [comment]
Generally, the explanations and info are above the config options so a user doesn't have to scroll forever to see things, but I can move it

**Comment by dwbrown2** [comment]
Open to other locations, but this is the primary open README for installing Kubecost. Logging detail that close to the install steps feels like we run the risk of distracting / overwhelming a first time user. Maybe that's not the right way of phrasing... let me know if I can articulate better.

**Comment by dramich** [comment]
Makes sense, moved it to the bottom

**Pull request merged**
