### PR TITLE
Add "persistentVolume.storageClass"

### PR DESCRIPTION
**Pull request by matthope**

### CODE REVIEW

**Comment by AjayTripathy** [comment]
Thanks for this PR! Looks like a great addition, let us test and get this submitted.

**Comment by AjayTripathy** [comment]
This LGTM! Thanks for your contribution @matthope and review @egeland

**Comment by cep21** [comment]
Should we add this to all the persistent volumes?

**Comment by dwbrown2** [comment]
@cep21 I actually think it should be available on all now! Which PV are you looking to change storageclass on?

**Comment by cep21** [comment]
I think it sets it on `kubecost-cost-analyzer`, but not the other things it makes like `kubecost-prometheus-server` and `kubecost-prometheus-alertmanager`

**Comment by dwbrown2** [comment]
Those can actually be set in our sub-charts. For example, in our values you can set `prometheus.alertmanager.persistentVolume.storageClass`. Let me know if I can share more!

**Pull request merged**
