### PR TITLE
increase scaling factors [Do not merge]

### PR DESCRIPTION
**Pull request by AjayTripathy**
Sample scaled thanos values as of 0.19-- do not merge.

### CODE REVIEW

**Comment by michaelmdresser** [comment]
Can we close this PR? Should we also add some documentation around these parameters for our own scale testing?

**Comment by AjayTripathy** [comment]
I've been leaving this open as a convenient place to link users who need sample values.yaml files as a PR with diffs. We're starting a set of docs to help users with this in general-- once we've published something more official, I will close.

**Comment by AdamStack18** [comment]
@dwbrown2 See Ajay's last comment.  Who should we get on creating this documentation?

**Comment by dwbrown2** [comment]
@AjayTripathy started a doc this week!

**Pull request closed without merging**
