### PR TITLE
[draft] chart for minimizing prom metrics

### PR DESCRIPTION
**Pull request by AjayTripathy**
Do not merge, test to see how much prom utilization drops on these configs.

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-79) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by AjayTripathy** [comment]
User reports that modifying these values via argoCD did not work for the regex updates.

**Comment by AjayTripathy** [comment]
After manually updating this and letting the instance stabilize, we saw a drop of roughly 50% on memory consumption.

**Comment by Adam-Stack-PM** [comment]
Marking as stale because this PR has had no recent activity. It will be closed in seven days if no further activity occurs.

**Comment by chipzoller** [comment]
Closing as stale.

**Pull request closed without merging**
