### PR TITLE
Add ALLOCATION_NODE_LABEL_ENABLED and ALLOCATION_NODE_LABEL_INCLUDE_LIST env vars

### PR DESCRIPTION
**Pull request by nikovacevic**
Required for https://github.com/opencost/opencost/pull/1618

### CODE REVIEW

**Comment by dwbrown2** [comment]
Should this default list be moved to our values file? cc @kwombach12

**Comment by kwombach12** [comment]
Absolutely! Is this the 'values' file you're referring to: https://github.com/kubecost/cost-analyzer-helm-chart/blob/master/README.md#config-options? @dwbrown2

**Comment by nikovacevic** [comment]
Yep. Just putting it here until we have a name for it, within `values.yaml` -- what do we think?

```yaml
kubecostModel:
  allocation:
    nodeLabels:
      enabled: true
      whiteList: "label1,label2,etc."
```

**Comment by kwombach12** [comment]
I think the name: `nodeLabels.whitelist` would make sense. Users could pass a list of the labels they want access to

**Comment by michaelmdresser** [comment]
Not blocking, but if its not too late, perhaps we could call it `allowlist` in the allow/deny fashion?

**Comment by nikovacevic** [comment]
Doesn't make a difference to me. In fact, I think Sean once called a Cloud Cost thing an "include list" -- do you have a preference @kwombach12 @dwbrown2 ?

**Comment by kwombach12** [comment]
@nikovacevic I like `includeList`. People have been moving away from white/black list for a variety of reasons so that makes a lot of sense to me.

**Review by saweber — APPROVED** [review]

**Comment by dwbrown2** [comment]
@nikovacevic aiming for 1.100 with this?

**Comment by nikovacevic** [comment]
@dwbrown2 yep!

**Comment by kc-adawson** [comment]
@dwbrown2 @nikovacevic @kwombach12 Hey guys, checking on the status of this one - Looks like it merged, is this now available as of 1.100.1?

**Comment by kwombach12** [comment]
@kc-adawson I believe it is! @nikovacevic correct me if im wrong

**Comment by kc-adawson** [comment]
@kwombach12 Confirmired this works on 1.100.1. 



Last question, if the includeList is not set, will it collect all node labels by default?

**Comment by kwombach12** [comment]
@kc-adawson I don't think it collects all node labels by default. By default, I believe we collect these labels:
`node.kubernetes.io/instance-type`, `topology.kubernetes.io/region`, `topology.kubernetes.io/zone`

**Comment by nikovacevic** [comment]
Kai is correct. It's deployed and there is a small "include list" that can be replaced in helm configuration.

**Comment by kc-adawson** [comment]
@nikovacevic @kwombach12 We have this deployed but the user is only seeing it working in /allocations and not anywhere else - When they go to filter Request Rightsizing by the same label, the page does not load anything. Would these labels be expected to work within Request Rightsizing? If not this may be a bug.

**Comment by nikovacevic** [comment]
Request Sizing uses the Allocation API, so if it's in Allocation it should be good-to-go for Request Sizing without any other work. And IIRC @srpomeroy even tested that exact use case when the feature had been merged, and was able to get it working.

Do you have a repro we can see @kc-adawson?

**Comment by kc-adawson** [comment]
@nikovacevic Repro here - http://acdc9ca48678c4e938348860722a922f-1516114798.us-east-2.elb.amazonaws.com:9090/request-sizing?window=7d&algorithmCPU=max&algorithmRAM=max&qCPU=0.95&qRAM=0.95&targetCPUUtilization=0.8&targetRAMUtilization=0.8&filter=W3sicHJvcGVydHkiOiJsYWJlbCIsInZhbHVlIjoiYmV0YS5rdWJlcm5ldGVzLmlvL29zIiwiZXF1YWxpdHkiOiI6In1d&profile=custom

Using "beta.kubernetes.io/os" which works in Allocation:

http://acdc9ca48678c4e938348860722a922f-1516114798.us-east-2.elb.amazonaws.com:9090/allocations?agg=label%3Abeta.kubernetes.io%2Fos

**Comment by kc-adawson** [comment]
@nikovacevic Hey Niko wanted to ping on this - I have updated the repro above to v1.100.2 and still see the filtering issue on the Rightsizing UI

**Comment by kc-adawson** [comment]
@nikovacevic So I realized the API returns the following when I use that nodeLabel, it seems to not auto-detect the containers that are related to the node label so theres nothing to show in the list:

`curl -G -d 'algorithmCPU=max' -d 'algorithmRAM=max' -d 'targetCPUUtilization=0.8' -d 'targetRAMUtilization=0.8' -d 'window=3d' --data-urlencode 'filter=label[beta.kubernetes.io/os]:"linux"' http://acdc9ca48678c4e938348860722a922f-1516114798.us-east-2.elb.amazonaws.com:9090/model/savings/requestSizingV2`

Response: Recommending requests from data: CPU algorithm set to max but no max data is available

**Comment by kc-adawson** [comment]
@nikovacevic @kwombach12 @dwbrown2 Another thing here - I added "beta.kubernetes.io/os" to the Product label group instead of a directly added label. This allows me to see the containers associated with "beta.kubernetes.io/os:linux"

http://acdc9ca48678c4e938348860722a922f-1516114798.us-east-2.elb.amazonaws.com:9090/allocations?agg=product

Kapture 2023-02-16 at 09 23 27

If I had the ability to filter by "Product" in Rightsizing, I would be able to see these associated containers with the node Label

 example on API - 'filter=product:"linux"' (this is not currently supported in filtersV2)
 
 Mockup:

**Comment by kc-adawson** [comment]
Right now the ask is for some kind of filter on rightsizing to include these new "nodeLabels" in features

I have a "nodeLabel" that is getting collected on this sandbox called "beta.kubernetes.io/ios". 

image

I can add it directly to allocation as a label, but then it does not show me the associated containers.

To get those, I've added it to the "Product" label map.



You can see my one value here, "Linux" when I sort by product

image

When I drill into details, we do know which containers are associated with this "linux" tag due to being in the "Product" group. 



We have no option to sort by product in Rightsizing, so I was trying to filter by the label of "beta.kubernetes.io/os=linux" for rightsizing, or even containers with tag key "beta.kubernetes.io/os" and any value. I also tried this with a simple app:kubecost: Doing this seems to crash the page with the following errors:

image

I think the "Label" filter anywhere in the product (rightsizing/allocation/alerts) should allow people to filter by a combo of any "label" we collect - whether its a Label, nodeLabel, or Annotation, they should all be available as a "label"

**Comment by kc-adawson** [comment]
Simplified outstanding issue into this new issue - https://github.com/kubecost/cost-analyzer-frontend/issues/1728. Boiled it down to 2 API calls.

**Pull request merged**
