### PR TITLE
Fix: Bump chart version, and condition must include "productKey.enabled"

### LINKED ISSUE #2056: productKey.enabled is not used cleanly
Thanks for your interest in Kubecost!  To ensure you get the help you need, please follow these guidelines:

- If you have questions about product functionality/usage or need assistance with product installation/configuration, please email support@kubecost.com, where our support engineering team will be happy to help!
- If you have a reproducible bug or a feature request, you're in the right place.  Please include the information requested below.

---
# For reproducible bugs, please provide the following

**Describe the bug**  

**To Reproduce**  
3. See error

**Expected behavior**  

**Screenshots**  

**Collect logs (please complete the following information):**
- Run `helm ls` and paste the output here:
- If the pod is stuck in init, run `kubectl logs <kubecost-cost-analyzer pod name> -n kubecost -c cost-analyzer-init` and paste output here:
- If a page is broken or not loading, open your javascript developer console and paste the ouput here:
- Run `kubectl logs <kubecost-cost-analyzer pod name> -n kubecost -c cost-analyzer-server` and paste the output here:
- Run `kubectl logs <kubecost-cost-analyzer pod name> -n kubecost -c cost-model` and paste the output here:
- Run `kubectl logs <kubecost-cost-analyzer pod name> -n kubecost -c cost-analyzer-frontend` and paste the output here:

---
# For feature requests, please provide the following:

**What problem are you trying to solve?**  

**Describe the solution you'd like**  

**Describe alternatives you've considered**  

**How would users interact with this feature?**

### PR DESCRIPTION
**Pull request by abdennour**
## What does this PR change?

Fixes #2056

## Does this PR rely on any other PRs?

- 
- 

## Links to Issues or ZD tickets this PR addresses or fixes

- 
-

### CODE REVIEW

**Comment by thomasvn** [comment]
@abdennour Thanks for the PR! This looks great. Could you test the PR by running `helm template`?

Once with both of these configured:

* `.Values.kubecostProductConfigs.productKey.enabled`
* `.Values.kubecostProductConfigs.productKey.secretname`

And then with only one of each configured:

* `.Values.kubecostProductConfigs.productKey.enabled`
* `.Values.kubecostProductConfigs.productKey.secretname`

**Comment by abdennour** [comment]
Ok ! Question : did you require to increase version in chart.yaml ?

**Comment by thomasvn** [comment]
@abdennour Yes go ahead and set your local [Chart.yaml](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/Chart.yaml)'s `appVersion` and `version` to match our current [release number](https://github.com/kubecost/cost-analyzer-helm-chart/releases) (v1.101.2)!

**Comment by thomasvn** [comment]
I'll work with the team to get this fixed on the `develop` branch

**Comment by abdennour** [comment]
Thank you @thomasvn  !  I will push requested changes

**Comment by abdennour** [comment]
version is adjusted
and tests are done: 
```sh
➜  cost-analyzer git:(patch-1) helm template . --set kubecostProductConfigs.productKey.enabled=false --set kubecostProductConfigs.productKey.secretname=xyz | grep xyz 2> /dev/null
➜  cost-analyzer git:(patch-1) helm template . --set kubecostProductConfigs.productKey.enabled=true --set kubecostProductConfigs.productKey.secretname=xyz | grep xyz 2> /dev/null
            secretName: xyz
➜  cost-analyzer git:(patch-1) 
```

@thomasvn  please FYA to approve and merge

**Review by thomasvn — APPROVED** [review]
@abdennour Thanks for testing, looks great!

**Pull request merged**
