### PR TITLE
Add support to use already existing prority class to address #1097

### PR DESCRIPTION
**Pull request by AshutoshNirkhe**
## Does this PR rely on any other PRs?

- 
- 

## Links to Issues or ZD tickets this PR addresses or fixes

- 
-

### CODE REVIEW

**Review by nikovacevic — CHANGES_REQUESTED** [review]
This version looks better to me. Thank you! Unfortunately, my original feedback included syntax that Helm doesn't support. My apologies @AshutoshNirkhe. Here's the actual syntax for those two boolean expressions:
```helm
{{- if eq (len .Values.priority.name) 0 }}
```
```helm
{{- if gt (len .Values.priority.name) 0 }}
```

The other thing is that, if `.Values.priority.enabled` is set to `true`, but `name` is not given at all, we'll get an error. It must be `name: ""`. Thus the default should likely be `""`.

Do you have concerns about any of this, @AjayTripathy?

**Comment by AjayTripathy** [comment]
> The other thing is that, if .Values.priority.enabled is set to true, but name is not given at all, we'll get an error. It must be name: "". Thus the default should likely be "".

Since these are both new fields, it should be ok to just set the default to "" and .Values.priority.enabled to true, so I don't have concerns there.

**Comment by AshutoshNirkhe** [comment]
> This version looks better to me. Thank you! Unfortunately, my original feedback included syntax that Helm doesn't support. My apologies @AshutoshNirkhe. Here's the actual syntax for those two boolean expressions:
> 
> ```
> {{- if eq (len .Values.priority.name) 0 }}
> ```
> 
> ```
> {{- if gt (len .Values.priority.name) 0 }}
> ```
> 
> The other thing is that, if `.Values.priority.enabled` is set to `true`, but `name` is not given at all, we'll get an error. It must be `name: ""`. Thus the default should likely be `""`.
> 
> Do you have concerns about any of this, @AjayTripathy?

@nikovacevic updated as per your comment. Could you please review/merge if all is good now ?

**Review by nikovacevic — APPROVED** [review]
LGTM. Thank you @AshutoshNirkhe.

**Pull request merged**
